-- Societies commissioned before this system existed: Amrapali Princely Estate.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "Amrapali Princely Estate"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ Amrapali Princely Estate ════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-amrapali-princely-estate-contract';
DELETE FROM contracts   WHERE id = 'bf-amrapali-princely-estate-contract';
DELETE FROM agreements  WHERE id = 'bf-amrapali-princely-estate-agreement';
DELETE FROM offers      WHERE id = 'bf-amrapali-princely-estate-offer';
DELETE FROM demo_reports WHERE id = 'bf-amrapali-princely-estate-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-amrapali-princely-estate-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-amrapali-princely-estate-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-amrapali-princely-estate-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-amrapali-princely-estate-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-amrapali-princely-estate-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-amrapali-princely-estate-survey';
DELETE FROM pipelines   WHERE id = 'bf-amrapali-princely-estate-pipe';
DELETE FROM engagements WHERE id = 'bf-amrapali-princely-estate-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'Amrapali Princely Estate';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'Amrapali Princely Estate'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'Amrapali Princely Estate'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'Amrapali Princely Estate';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-amrapali-princely-estate-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'Amrapali Princely Estate' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-amrapali-princely-estate-pipe', s.id, 'lighting', 'active_billing',
       'Amrapali Princely Estate', NULL, '2026-02-26'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'Amrapali Princely Estate' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-amrapali-princely-estate-survey', 'bf-amrapali-princely-estate-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-amrapali-princely-estate-ckt-1', s.id, 'bf-amrapali-princely-estate-survey', 'lighting', 'basement',
       140, 2310, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2025-12-20'::date, '2026-02-08'::date,
       66.31, 65.09,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Amrapali Princely Estate' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-amrapali-princely-estate-ckt-1-inv', 'bf-amrapali-princely-estate-survey', 'Basement', 'basement',
        2310, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-amrapali-princely-estate-ckt-1-dev-1', 'bf-amrapali-princely-estate-ckt-1', dt.id, 140, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1', 'bf-amrapali-princely-estate-ckt-1', 1, 40,
        19.14, 6.68, 65.09926854754441, false,
        NULL, 'Initial pilot, 6 pre days 21-26 Dec 2025 averaging 19.1433 against a stated 19.14, then 5 days 29 Dec-02 Jan averaging 6.6820 against 6.68. Report''s own savings 65.09%.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-pre-2025-12-21', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-21'::date, 19.04, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-pre-2025-12-22', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-22'::date, 19.19, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-pre-2025-12-23', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-23'::date, 19.1, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-pre-2025-12-24', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-24'::date, 19.17, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-pre-2025-12-25', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-25'::date, 19.16, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-pre-2025-12-26', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-26'::date, 19.2, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-post-2025-12-29', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-29'::date, 6.32, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-post-2025-12-30', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-30'::date, 6.88, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-post-2025-12-31', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-12-31'::date, 6.8, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-post-2025-01-01', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-01-01'::date, 6.71, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-1-post-2025-01-02', 'bf-amrapali-princely-estate-ckt-1-demo-1',
        '2025-01-02'::date, 6.7, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2', 'bf-amrapali-princely-estate-ckt-1', 2, 100,
        47.17, 18.53, 60.71655713377147, false,
        NULL, 'Extended validation, 16 pre days 14-29 Jan 2026 averaging 47.1706 against a stated 47.17 (printed as two stacked halves, the Average in the first). Post table''s 8 days average 18.7675 against a stated 18.53 - the report''s own 60.72% uses 18.53, so that is the figure of record and the days stay as measured.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-14', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-14'::date, 47.91, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-15', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-15'::date, 47.92, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-16', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-16'::date, 48.04, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-17', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-17'::date, 46.62, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-18', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-18'::date, 47.5, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-19', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-19'::date, 47.21, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-20', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-20'::date, 47.51, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-21', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-21'::date, 47.4, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-22', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-22'::date, 47.37, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-23', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-23'::date, 46.4, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-24', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-24'::date, 46.74, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-25', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-25'::date, 46.64, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-26', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-26'::date, 46.44, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-27', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-27'::date, 46.77, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-28', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-28'::date, 47.14, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-pre-2026-01-29', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-01-29'::date, 47.12, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-post-2026-02-09', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-02-09'::date, 18.92, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-post-2026-02-10', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-02-10'::date, 18.87, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-post-2026-02-11', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-02-11'::date, 18.5, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-post-2026-02-12', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-02-12'::date, 17.77, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-post-2026-02-13', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-02-13'::date, 18.61, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-post-2026-02-14', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-02-14'::date, 19.31, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-post-2026-02-15', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-02-15'::date, 19.15, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-amrapali-princely-estate-ckt-1-demo-2-post-2026-02-16', 'bf-amrapali-princely-estate-ckt-1-demo-2',
        '2026-02-16'::date, 19.01, 'post') ON CONFLICT DO NOTHING;
UPDATE circuits
   SET benchmark_override_pct = 65.09,
       benchmark_override_reason = 'Agreement states 65.09%; the demos on record give 62.9079%. The agreed figure is what this society is billed against.',
       benchmark_override_by_id = (SELECT a.id FROM admin_users a WHERE a.id = 'sys-data-import'),
       benchmark_override_at = now()
 WHERE id = 'bf-amrapali-princely-estate-ckt-1' AND benchmark_override_pct IS NULL;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-amrapali-princely-estate-demo-report', 'bf-amrapali-princely-estate-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-amrapali-princely-estate-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 140, "representedLightCount": 2310, "extrapolationFactor": 16.5, "preInstallBaseline": 66.31, "postInstallAverage": 25.21, "savedKwhPerDay": 41.1, "benchmarkSavingsPct": 65.09, "projectedSavedKwhPerDay": 712.1595, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2026-02-26'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-amrapali-princely-estate-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-amrapali-princely-estate-offer', 'bf-amrapali-princely-estate-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-amrapali-princely-estate-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 140, "representedLightCount": 2310, "benchmarkSavingsPct": 65.09, "preInstallBaseline": 66.31, "projectedSavedKwhPerDay": 43.1612}]'::jsonb,
       10, 56.5632, 6.65, 36,
       62541.71, '2026-02-26'::date, a.id,
       '2026-02-26'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'Amrapali Princely Estate'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-amrapali-princely-estate-agreement', 'bf-amrapali-princely-estate-pipe', 'bf-amrapali-princely-estate-offer', '2026-02-26'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2026-02-11'::date, '2026-02-11'::date,
       '2026-02-26'::date,
       'Documents/Amrapali_Princely_Estate/2026-02/Agreements/Amrapali_Princely_Estate_Agreement_2026-02-26.pdf',
       'Amrapali_Princely_Estate_Agreement_2026-02-26.pdf',
       -- The scan reaches us the day after signing.
       ('2026-02-26'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-amrapali-princely-estate-contract', 'bf-amrapali-princely-estate-pipe', s.id, 'lighting', 'bf-amrapali-princely-estate-agreement', 'active',
       '2026-04-02'::date, ('2026-04-02'::date + '36 months'::interval),
       '2026-04-02'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Amrapali Princely Estate' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-amrapali-princely-estate-terms', 'bf-amrapali-princely-estate-contract', 1, '2026-04-02'::date, 'negotiated_fixed',
       10, 56.5632, 6.65,
       '[{"circuitId": "bf-amrapali-princely-estate-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 140, "representedLightCount": 2310, "benchmarkSavingsPct": 65.09, "preInstallBaseline": 66.31, "projectedSavedKwhPerDay": 43.1612}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
