-- Societies commissioned before this system existed: ATS Greens Paradiso.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "ATS Greens Paradiso"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ ATS Greens Paradiso ═════════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-ats-greens-paradiso-contract';
DELETE FROM contracts   WHERE id = 'bf-ats-greens-paradiso-contract';
DELETE FROM agreements  WHERE id = 'bf-ats-greens-paradiso-agreement';
DELETE FROM offers      WHERE id = 'bf-ats-greens-paradiso-offer';
DELETE FROM demo_reports WHERE id = 'bf-ats-greens-paradiso-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-ats-greens-paradiso-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-ats-greens-paradiso-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-ats-greens-paradiso-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-ats-greens-paradiso-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-ats-greens-paradiso-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-ats-greens-paradiso-survey';
DELETE FROM pipelines   WHERE id = 'bf-ats-greens-paradiso-pipe';
DELETE FROM engagements WHERE id = 'bf-ats-greens-paradiso-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'ATS Greens Paradiso';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'ATS Greens Paradiso'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'ATS Greens Paradiso'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'ATS Greens Paradiso';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-ats-greens-paradiso-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'ATS Greens Paradiso' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-ats-greens-paradiso-pipe', s.id, 'lighting', 'active_billing',
       'ATS Greens Paradiso', NULL, '2026-03-22'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'ATS Greens Paradiso' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-ats-greens-paradiso-survey', 'bf-ats-greens-paradiso-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-ats-greens-paradiso-ckt-1', s.id, 'bf-ats-greens-paradiso-survey', 'lighting', 'basement',
       40, 951, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2026-01-06'::date, '2026-01-17'::date,
       18.71, 64.43,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'ATS Greens Paradiso' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-ats-greens-paradiso-ckt-1-inv', 'bf-ats-greens-paradiso-survey', 'Basement', 'basement',
        951, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-ats-greens-paradiso-ckt-1-dev-1', 'bf-ats-greens-paradiso-ckt-1', dt.id, 40, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1', 'bf-ats-greens-paradiso-ckt-1', 1, 40,
        18.71, 6.66, 64.40406199893106, false,
        NULL, '5 pre days 07-11 Jan 2026 averaging 18.7140 against a stated 18.71, then 4 days 18-21 Jan averaging 6.6575 against 6.66. Transcribed from the rendered PDF, which has no extractable text.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-pre-2026-01-07', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-07'::date, 18.71, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-pre-2026-01-08', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-08'::date, 18.73, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-pre-2026-01-09', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-09'::date, 18.73, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-pre-2026-01-10', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-10'::date, 18.73, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-pre-2026-01-11', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-11'::date, 18.67, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-post-2026-01-18', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-18'::date, 6.68, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-post-2026-01-19', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-19'::date, 6.82, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-post-2026-01-20', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-20'::date, 6.43, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-ats-greens-paradiso-ckt-1-demo-1-post-2026-01-21', 'bf-ats-greens-paradiso-ckt-1-demo-1',
        '2026-01-21'::date, 6.7, 'post') ON CONFLICT DO NOTHING;
UPDATE circuits
   SET benchmark_override_pct = 64.43,
       benchmark_override_reason = 'Agreement states 64.43%; the demos on record give 64.4041%. The agreed figure is what this society is billed against.',
       benchmark_override_by_id = (SELECT a.id FROM admin_users a WHERE a.id = 'sys-data-import'),
       benchmark_override_at = now()
 WHERE id = 'bf-ats-greens-paradiso-ckt-1' AND benchmark_override_pct IS NULL;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-ats-greens-paradiso-demo-report', 'bf-ats-greens-paradiso-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-ats-greens-paradiso-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 40, "representedLightCount": 951, "extrapolationFactor": 23.775, "preInstallBaseline": 18.71, "postInstallAverage": 6.66, "savedKwhPerDay": 12.05, "benchmarkSavingsPct": 64.43, "projectedSavedKwhPerDay": 286.6041, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2026-03-22'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-ats-greens-paradiso-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-ats-greens-paradiso-offer', 'bf-ats-greens-paradiso-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-ats-greens-paradiso-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 40, "representedLightCount": 951, "benchmarkSavingsPct": 64.43, "preInstallBaseline": 18.71, "projectedSavedKwhPerDay": 12.0549}]'::jsonb,
       5, 60, 6.30, 36,
       21663.78, '2026-03-22'::date, a.id,
       '2026-03-22'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'ATS Greens Paradiso'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-ats-greens-paradiso-agreement', 'bf-ats-greens-paradiso-pipe', 'bf-ats-greens-paradiso-offer', '2026-03-22'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2026-03-17'::date, '2026-03-17'::date,
       '2026-03-22'::date,
       'Documents/ATS_Greens_Paradiso/2026-03/Agreements/ATS_Greens_Paradiso_Agreement_2026-03-22.pdf',
       'ATS_Greens_Paradiso_Agreement_2026-03-22.pdf',
       -- The scan reaches us the day after signing.
       ('2026-03-22'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-ats-greens-paradiso-contract', 'bf-ats-greens-paradiso-pipe', s.id, 'lighting', 'bf-ats-greens-paradiso-agreement', 'active',
       '2026-06-01'::date, ('2026-06-01'::date + '36 months'::interval),
       '2026-06-01'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'ATS Greens Paradiso' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-ats-greens-paradiso-terms', 'bf-ats-greens-paradiso-contract', 1, '2026-06-01'::date, 'negotiated_fixed',
       5, 60, 6.30,
       '[{"circuitId": "bf-ats-greens-paradiso-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 40, "representedLightCount": 951, "benchmarkSavingsPct": 64.43, "preInstallBaseline": 18.71, "projectedSavedKwhPerDay": 12.0549}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
