-- Societies commissioned before this system existed: Mahagun Puram.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "Mahagun Puram"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ Mahagun Puram ═══════════════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-mahagun-puram-contract';
DELETE FROM contracts   WHERE id = 'bf-mahagun-puram-contract';
DELETE FROM agreements  WHERE id = 'bf-mahagun-puram-agreement';
DELETE FROM offers      WHERE id = 'bf-mahagun-puram-offer';
DELETE FROM demo_reports WHERE id = 'bf-mahagun-puram-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-mahagun-puram-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-mahagun-puram-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-mahagun-puram-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-mahagun-puram-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-mahagun-puram-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-mahagun-puram-survey';
DELETE FROM pipelines   WHERE id = 'bf-mahagun-puram-pipe';
DELETE FROM engagements WHERE id = 'bf-mahagun-puram-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'Mahagun Puram';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'Mahagun Puram'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'Mahagun Puram'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'Mahagun Puram';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-mahagun-puram-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'Mahagun Puram' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-mahagun-puram-pipe', s.id, 'lighting', 'active_billing',
       'Mahagun Puram', NULL, '2025-11-16'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'Mahagun Puram' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-mahagun-puram-survey', 'bf-mahagun-puram-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-mahagun-puram-ckt-1', s.id, 'bf-mahagun-puram-survey', 'lighting', 'basement',
       44, 792, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2025-08-03'::date, '2025-09-21'::date,
       20.24, 62.70,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.',
                          'deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo"]'::jsonb,
                          'basisNote', '44 tube lights at 20W running 24h; theoretical 21.12 kWh/day against a measured 20.24, a -4.17% variance the report records as within range. NO OVERRIDE: (20.24-7.55)/20.24 = 62.6976%, the agreed 62.70%. Both tables reproduce their stated averages - 4 pre days 04-07 Aug 2025 average 20.2375 against 20.24, 4 post days 22-25 Sep average 7.5450 against 7.55. THIS IS THE REPORT THE ''w.r.t 20.24 kWh'' LEFTOVER COMES FROM. Here the header is correct: 20.24 is this circuit''s own baseline. French Apartment''s and RG Residency''s reports carry the same header over entirely different baselines, so it was copied from this one and never updated. Neither date is stated: meter install taken as the day before the first pre-install reading (04 Aug 2025), replacement as the day before the post-install readings start (22 Sep).'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Mahagun Puram' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-mahagun-puram-ckt-1-inv', 'bf-mahagun-puram-survey', 'Basement', 'basement',
        792, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-mahagun-puram-ckt-1-dev-1', 'bf-mahagun-puram-ckt-1', dt.id, 44, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-mahagun-puram-ckt-1-demo-1', 'bf-mahagun-puram-ckt-1', 1, 44,
        20.24, 7.55, 62.69762845849802, false,
        NULL, '4 pre days 04-07 Aug 2025 averaging 20.2375 against a stated 20.24, then 4 days 22-25 Sep averaging 7.5450 against 7.55.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-mahagun-puram-ckt-1-demo-1-pre-2025-08-04', 'bf-mahagun-puram-ckt-1-demo-1',
        '2025-08-04'::date, 20.63, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-mahagun-puram-ckt-1-demo-1-pre-2025-08-05', 'bf-mahagun-puram-ckt-1-demo-1',
        '2025-08-05'::date, 20.09, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-mahagun-puram-ckt-1-demo-1-pre-2025-08-06', 'bf-mahagun-puram-ckt-1-demo-1',
        '2025-08-06'::date, 20.21, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-mahagun-puram-ckt-1-demo-1-pre-2025-08-07', 'bf-mahagun-puram-ckt-1-demo-1',
        '2025-08-07'::date, 20.02, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-mahagun-puram-ckt-1-demo-1-post-2025-09-22', 'bf-mahagun-puram-ckt-1-demo-1',
        '2025-09-22'::date, 7.4, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-mahagun-puram-ckt-1-demo-1-post-2025-09-23', 'bf-mahagun-puram-ckt-1-demo-1',
        '2025-09-23'::date, 7.17, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-mahagun-puram-ckt-1-demo-1-post-2025-09-24', 'bf-mahagun-puram-ckt-1-demo-1',
        '2025-09-24'::date, 7.84, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-mahagun-puram-ckt-1-demo-1-post-2025-09-25', 'bf-mahagun-puram-ckt-1-demo-1',
        '2025-09-25'::date, 7.77, 'post') ON CONFLICT DO NOTHING;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-mahagun-puram-demo-report', 'bf-mahagun-puram-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-mahagun-puram-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 44, "representedLightCount": 792, "extrapolationFactor": 18.0, "preInstallBaseline": 20.24, "postInstallAverage": 7.55, "savedKwhPerDay": 12.69, "benchmarkSavingsPct": 62.7, "projectedSavedKwhPerDay": 228.4286, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2025-11-16'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-mahagun-puram-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-mahagun-puram-offer', 'bf-mahagun-puram-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-mahagun-puram-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 44, "representedLightCount": 792, "benchmarkSavingsPct": 62.7, "preInstallBaseline": 20.24, "projectedSavedKwhPerDay": 12.6905}]'::jsonb,
       5, 53.1394, 6.93, 36,
       23221.44, '2025-11-16'::date, a.id,
       '2025-11-16'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'Mahagun Puram'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at, deviation_note,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-mahagun-puram-agreement', 'bf-mahagun-puram-pipe', 'bf-mahagun-puram-offer', '2025-11-16'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2025-11-15'::date, '2025-11-15'::date,
       '2025-11-16'::date,
       -- How this deal's figures were arrived at, in the field named for it.
       -- These societies predate the system and share no single method, so
       -- the basis travels with the agreement rather than living in a CSV.
       'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: extrapolation-theoretical, fee-device-charge-plus-share-of-net, additional-light-clause-not-applied, report-share-differs-from-agreement. SOURCE IS THE USER''S PASTED TEXT for the agreement and demo report; the invoices are real files. Every agreement figure reconciles: 700 x 20W x 24h x 30 = 10,080 kWh/month, 62.70% of it is 6,320 kWh at Rs 6.93 = Rs 43,798, less Rs 14,000 devices = Rs 29,798 net, split into Rs 23,273 and Rs 6,525 - which sum correctly but are 78.10/21.90, not the 78/22 the annexure labels them. THE ADDITIONAL-LIGHT CLAUSE WAS NOT APPLIED. 792 lights went in against a 700 minimum, and the annexure prices the extra at Rs 33 each, which would give Rs 20,525 + 92 x 33 = Rs 23,561. The June 2026 invoice, a full month, bills 792 x Rs 29.32 = Rs 23,221.44 - and Rs 29.32 is exactly the base rate, Rs 20,525/700. So every light is billed at the base rate and Rs 23,221.44 is what is recorded, with the share derived from it. Billing from 4 May 2026 - the first invoice says so on its face, ''for the month of May 2026 - From 4th May'', 28 days. That invoice prorates to exactly 0.9 of the monthly rate (Rs 26.39 of Rs 29.32) rather than 28/31, which would have been Rs 26.48. Agreement generated 15 Nov 2025 and signed 16 Nov (the user). Tolerance +/-5%, stated in clause 6. The report''s own ''50% of these verified savings'' matches neither the agreement nor the invoice.',
       'Documents/Mahagun_Puram/2025-11/Agreements/Mahagun_Puram_Agreement_2025-11-16.pdf',
       'Mahagun_Puram_Agreement_2025-11-16.pdf',
       -- The scan reaches us the day after signing.
       ('2025-11-16'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-mahagun-puram-contract', 'bf-mahagun-puram-pipe', s.id, 'lighting', 'bf-mahagun-puram-agreement', 'active',
       '2026-05-04'::date, ('2026-05-04'::date + '36 months'::interval),
       '2026-05-04'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Mahagun Puram' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-mahagun-puram-terms', 'bf-mahagun-puram-contract', 1, '2026-05-04'::date, 'negotiated_fixed',
       5, 53.1394, 6.93,
       '[{"circuitId": "bf-mahagun-puram-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 44, "representedLightCount": 792, "benchmarkSavingsPct": 62.7, "preInstallBaseline": 20.24, "projectedSavedKwhPerDay": 12.6905}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
