-- Societies commissioned before this system existed: Elite Homz.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "Elite Homz"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ Elite Homz ══════════════════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-elite-homz-contract';
DELETE FROM contracts   WHERE id = 'bf-elite-homz-contract';
DELETE FROM agreements  WHERE id = 'bf-elite-homz-agreement';
DELETE FROM offers      WHERE id = 'bf-elite-homz-offer';
DELETE FROM demo_reports WHERE id = 'bf-elite-homz-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-elite-homz-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-elite-homz-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-elite-homz-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-elite-homz-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-elite-homz-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-elite-homz-survey';
DELETE FROM pipelines   WHERE id = 'bf-elite-homz-pipe';
DELETE FROM engagements WHERE id = 'bf-elite-homz-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'Elite Homz';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'Elite Homz'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'Elite Homz'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'Elite Homz';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-elite-homz-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'Elite Homz' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-elite-homz-pipe', s.id, 'lighting', 'active_billing',
       'Elite Homz', NULL, '2026-01-20'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'Elite Homz' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-elite-homz-survey', 'bf-elite-homz-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-elite-homz-ckt-1', s.id, 'bf-elite-homz-survey', 'lighting', 'basement',
       45, 961, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2025-11-12'::date, '2025-11-23'::date,
       22.01, 61.29,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.',
                          'deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo"]'::jsonb,
                          'basisNote', '45 tube lights at 20W running 24h; theoretical 21.60 kWh/day against a measured 22.01, a +1.89% variance the report records as within range. NO OVERRIDE: (22.01-8.52)/22.01 = 61.2903%, which is the agreed 61.29%. Both tables reproduce their stated averages - 6 pre days 13-18 Nov 2025 average 22.0083 against 22.01, 6 post days 24-29 Nov average 8.5183 against 8.52. Neither date is stated: meter install taken as the day before the first pre-install reading (13 Nov 2025), replacement as the day before the post-install readings start (24 Nov).'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Elite Homz' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-elite-homz-ckt-1-inv', 'bf-elite-homz-survey', 'Basement', 'basement',
        961, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-elite-homz-ckt-1-dev-1', 'bf-elite-homz-ckt-1', dt.id, 45, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-elite-homz-ckt-1-demo-1', 'bf-elite-homz-ckt-1', 1, 45,
        22.01, 8.52, 61.29032258064516, false,
        NULL, '6 pre days 13-18 Nov 2025 averaging 22.0083 against a stated 22.01, then 6 days 24-29 Nov averaging 8.5183 against 8.52. Transcribed from the user''s pasted text.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-pre-2025-11-13', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-13'::date, 22.06, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-pre-2025-11-14', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-14'::date, 22.09, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-pre-2025-11-15', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-15'::date, 22.08, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-pre-2025-11-16', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-16'::date, 21.63, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-pre-2025-11-17', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-17'::date, 22.1, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-pre-2025-11-18', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-18'::date, 22.09, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-post-2025-11-24', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-24'::date, 8.43, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-post-2025-11-25', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-25'::date, 8.47, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-post-2025-11-26', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-26'::date, 8.48, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-post-2025-11-27', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-27'::date, 8.38, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-post-2025-11-28', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-28'::date, 8.56, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-elite-homz-ckt-1-demo-1-post-2025-11-29', 'bf-elite-homz-ckt-1-demo-1',
        '2025-11-29'::date, 8.79, 'post') ON CONFLICT DO NOTHING;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-elite-homz-demo-report', 'bf-elite-homz-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-elite-homz-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 45, "representedLightCount": 961, "extrapolationFactor": 21.355556, "preInstallBaseline": 22.01, "postInstallAverage": 8.52, "savedKwhPerDay": 13.49, "benchmarkSavingsPct": 61.29, "projectedSavedKwhPerDay": 288.0849, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2026-01-20'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-elite-homz-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-elite-homz-offer', 'bf-elite-homz-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-elite-homz-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 45, "representedLightCount": 961, "benchmarkSavingsPct": 61.29, "preInstallBaseline": 22.01, "projectedSavedKwhPerDay": 13.4899}]'::jsonb,
       5, 63, 7.00, 36,
       22394.00, '2026-01-20'::date, a.id,
       '2026-01-20'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'Elite Homz'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at, deviation_note,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-elite-homz-agreement', 'bf-elite-homz-pipe', 'bf-elite-homz-offer', '2026-01-20'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2026-01-13'::date, '2026-01-13'::date,
       '2026-01-20'::date,
       -- How this deal's figures were arrived at, in the field named for it.
       -- These societies predate the system and share no single method, so
       -- the basis travels with the agreement rather than living in a CSV.
       'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: extrapolation-measured, minimum-light-clause-not-enforced, report-share-differs-from-agreement. SOURCE IS THE USER''S PASTED TEXT for the agreement and demo report (2026-08-28); the invoices are real files. The demo was 45 lights - the annexure''s ''55'' is a typo, confirmed by the user, and 45 is what the report''s own theoretical (45 x 20W x 24h = 21.60 kWh/day) and every figure after it use. LIGHT COUNT IS 961, confirmed by the user (2026-08-28) after an initial 400. All three invoices bill 961, and the arithmetic agrees: April and May are full months at Rs 22,394.00, which is the agreement''s Rs 23,815 scaled 961/1022 to the rupee, and FirsThing''s share of the savings at 961 lights works out to exactly the 37% the agreement states. Agreement made 27 Dec 2025, notarised 13 Jan 2026, signed 20 Jan 2026. Billing from 15 Mar 2026: the first invoice is dated 31 Mar for 17 days, and installation finished on or before 14 Mar (the user), so this one follows CON-22''s ordinary day-after rule. Monthly charge is Rs 19,220 of devices (961 x Rs 20) plus Rs 3,174 of services = Rs 22,394 ex-GST; the March invoice prorates only the device line cleanly (19,220 x 17/31 = 10,540 exactly). 1,022 lights agreed, 961 installed - the agreement''s clause that the full Rs 23,815 stays payable below the minimum was NOT enforced; the charge was scaled down instead. Tolerance +/-5%, stated in clause 6. The demo report''s own ''50% of these verified savings'' does not match the agreement''s 63/37 and is not used.',
       'Documents/Elite_Homz/2026-01/Agreements/Elite_Homz_Agreement_2026-01-20.pdf',
       'Elite_Homz_Agreement_2026-01-20.pdf',
       -- The scan reaches us the day after signing.
       ('2026-01-20'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-elite-homz-contract', 'bf-elite-homz-pipe', s.id, 'lighting', 'bf-elite-homz-agreement', 'active',
       '2026-03-15'::date, ('2026-03-15'::date + '36 months'::interval),
       '2026-03-15'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Elite Homz' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-elite-homz-terms', 'bf-elite-homz-contract', 1, '2026-03-15'::date, 'negotiated_fixed',
       5, 63, 7.00,
       '[{"circuitId": "bf-elite-homz-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 45, "representedLightCount": 961, "benchmarkSavingsPct": 61.29, "preInstallBaseline": 22.01, "projectedSavedKwhPerDay": 13.4899}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
