-- Societies commissioned before this system existed: French Apartment.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "French Apartment"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ French Apartment ════════════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-french-apartment-contract';
DELETE FROM contracts   WHERE id = 'bf-french-apartment-contract';
DELETE FROM agreements  WHERE id = 'bf-french-apartment-agreement';
DELETE FROM offers      WHERE id = 'bf-french-apartment-offer';
DELETE FROM demo_reports WHERE id = 'bf-french-apartment-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-french-apartment-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-french-apartment-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-french-apartment-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-french-apartment-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-french-apartment-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-french-apartment-survey';
DELETE FROM pipelines   WHERE id = 'bf-french-apartment-pipe';
DELETE FROM engagements WHERE id = 'bf-french-apartment-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'French Apartment';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'French Apartment'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'French Apartment'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'French Apartment';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-french-apartment-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'French Apartment' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-french-apartment-pipe', s.id, 'lighting', 'active_billing',
       'French Apartment', NULL, '2026-03-18'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'French Apartment' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-french-apartment-survey', 'bf-french-apartment-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-french-apartment-ckt-1', s.id, 'bf-french-apartment-survey', 'lighting', 'basement',
       55, 1066, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2025-11-04'::date, '2025-11-14'::date,
       25.00, 64.36,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.',
                          'deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo"]'::jsonb,
                          'basisNote', '55 tube lights at 20W running 24h; theoretical 26.40 kWh/day against a measured 25.00, a -5.32% variance the report records as within its +/-10% range. NO OVERRIDE: (25.00-8.91)/25.00 = 64.3600%, exactly the agreed 64.36%. Both tables reproduce their stated averages - 6 pre days 05-10 Nov 2025 average 24.9967 against 25.00, 4 post days 15-18 Nov average 8.9050 against 8.91. The post table is headed ''Savings % w.r.t 20.24 kWh'', which is a leftover: its own percentages only work against 25.00 (9.15 gives the stated 63.40% against 25.00, not against 20.24). Same shape as Amrapali Princely Estate''s ''w.r.t 23.96''. Neither date is stated: meter install taken as the day before the first pre-install reading (05 Nov 2025), replacement as the day before the post-install readings start (15 Nov).'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'French Apartment' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-french-apartment-ckt-1-inv', 'bf-french-apartment-survey', 'Basement', 'basement',
        1066, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-french-apartment-ckt-1-dev-1', 'bf-french-apartment-ckt-1', dt.id, 55, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-french-apartment-ckt-1-demo-1', 'bf-french-apartment-ckt-1', 1, 55,
        25.0, 8.91, 64.36, false,
        NULL, '6 pre days 05-10 Nov 2025 averaging 24.9967 against a stated 25.00, then 4 days 15-18 Nov averaging 8.9050 against 8.91. Transcribed from the user''s pasted text.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-pre-2025-11-05', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-05'::date, 24.98, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-pre-2025-11-06', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-06'::date, 24.99, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-pre-2025-11-07', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-07'::date, 24.99, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-pre-2025-11-08', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-08'::date, 24.98, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-pre-2025-11-09', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-09'::date, 24.97, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-pre-2025-11-10', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-10'::date, 25.07, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-post-2025-11-15', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-15'::date, 9.15, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-post-2025-11-16', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-16'::date, 8.8, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-post-2025-11-17', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-17'::date, 8.94, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-french-apartment-ckt-1-demo-1-post-2025-11-18', 'bf-french-apartment-ckt-1-demo-1',
        '2025-11-18'::date, 8.73, 'post') ON CONFLICT DO NOTHING;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-french-apartment-demo-report', 'bf-french-apartment-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-french-apartment-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 55, "representedLightCount": 1066, "extrapolationFactor": 19.381818, "preInstallBaseline": 25.0, "postInstallAverage": 8.91, "savedKwhPerDay": 16.09, "benchmarkSavingsPct": 64.36, "projectedSavedKwhPerDay": 311.8535, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2026-03-18'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-french-apartment-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-french-apartment-offer', 'bf-french-apartment-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-french-apartment-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 55, "representedLightCount": 1066, "benchmarkSavingsPct": 64.36, "preInstallBaseline": 25.0, "projectedSavedKwhPerDay": 16.09}]'::jsonb,
       5, 58, 6.15, 36,
       24165.52, '2026-03-18'::date, a.id,
       '2026-03-18'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'French Apartment'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at, deviation_note,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-french-apartment-agreement', 'bf-french-apartment-pipe', 'bf-french-apartment-offer', '2026-03-18'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2026-03-18'::date, '2026-03-18'::date,
       '2026-03-18'::date,
       -- How this deal's figures were arrived at, in the field named for it.
       -- These societies predate the system and share no single method, so
       -- the basis travels with the agreement rather than living in a CSV.
       'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: extrapolation-measured, billing-predates-agreement-execution, agreement-re-executed-after-changes. SOURCE IS THE USER''S PASTED TEXT for the agreement and demo report (2026-08-28). Every figure reconciles to the paisa: the pre-installation consumption 14,536.36 kWh/month is the demo''s MEASURED 25.00 kWh/day extrapolated over 55 lights to 1,066 (25.00/55 x 1066 x 30) - exact, not rounded - and 64.36% of it at Rs 6.15 gives Rs 57,536.94, split 58/42 for FirsThing''s Rs 24,165.52. 1,066 agreed and 1,066 installed, so the minimum clause does not bite. BILLING PREDATES EXECUTION, and the agreement says so itself: clause 21 sets the effective date at 24 Feb 2026 but the billing period at 1 Jan 2026 to 31 Dec 2028. It was then notarised and signed on 18 Mar 2026, a SECOND execution after changes - an earlier version was signed before Dec 2025 and is not on file (the user). So the contract on record was executed more than two months after the billing it governs began. The dates held here are the second signing. First invoice is for Jan 2026, so installation finished on or before 31 Dec 2025. Tolerance +/-5%, stated twice - in clause 6 and again in the performance guarantee. The demo report''s own ''42% of these verified savings'' AGREES with the agreement''s 58/42, unlike most of these.',
       'Documents/French_Apartment/2026-03/Agreements/French_Apartment_Agreement_2026-03-18.pdf',
       'French_Apartment_Agreement_2026-03-18.pdf',
       -- The scan reaches us the day after signing.
       ('2026-03-18'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-french-apartment-contract', 'bf-french-apartment-pipe', s.id, 'lighting', 'bf-french-apartment-agreement', 'active',
       '2026-01-01'::date, ('2026-01-01'::date + '36 months'::interval),
       '2026-01-01'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'French Apartment' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-french-apartment-terms', 'bf-french-apartment-contract', 1, '2026-01-01'::date, 'negotiated_fixed',
       5, 58, 6.15,
       '[{"circuitId": "bf-french-apartment-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 55, "representedLightCount": 1066, "benchmarkSavingsPct": 64.36, "preInstallBaseline": 25.0, "projectedSavedKwhPerDay": 16.09}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
