-- The 19 societies this business serves.
--
-- Business records: name, location, flat count, status. Their portal
-- accounts are deliberately NOT here — see scripts/make-data-migrations.py
-- for why, and how production creates them instead.

INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-mapsko-casa-bella', 'Mapsko Casa Bella', '350', 'Sector 82, Gurugram', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'mapsko casa bella|sector 82 gurugram') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-arihant-ambar', 'Arihant Ambar', '740', 'Sector 1, Greater Noida West', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'arihant ambar|sector 1 greater noida west') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-the-hyde-park', 'The Hyde Park', '1600', 'Sector 78, Noida', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'the hyde park|sector 78 noida') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-rg-residency', 'RG Residency', '1444', 'Sector 120, Noida', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'rg residency|sector 120 noida') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-french-apartment', 'French Apartment', '1066', 'Sector 16B, Greater Noida West', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'french apartment|sector 16b greater noida west') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-bestech-park-view-residency', 'Bestech Park View Residency', '400', 'Sector 3, Gurugram', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'bestech park view residency|sector 3 gurugram') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-amrapali-princely-estate', 'Amrapali Princely Estate', '2310', 'Sector 76, Noida', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'amrapali princely estate|sector 76 noida') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-elite-homz', 'Elite Homz', '961', 'Sector 77, Noida', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'elite homz|sector 77 noida') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-gaur-saundaryam', 'Gaur Saundaryam', '2362', 'Tech Zone 4, Greater Noida West', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'gaur saundaryam|tech zone 4 greater noida west') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-arihant-arden', 'Arihant Arden', '750', 'Sector 1, Greater Noida West', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'arihant arden|sector 1 greater noida west') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-mahagun-puram', 'Mahagun Puram', '792', 'NH-24, Ghaziabad', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'mahagun puram|nh 24 ghaziabad') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-pearls-gateway-towers', 'Pearls Gateway Towers', '559', 'Sector 44, Noida', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'pearls gateway towers|sector 44 noida') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-ats-greens-paradiso', 'ATS Greens Paradiso', '951', 'Sector Chi-04, Greater Noida', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'ats greens paradiso|sector chi 04 greater noida') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-kw-srishti', 'KW Srishti', '2100', 'Raj Nagar Extension, Ghaziabad', NULL, NULL, 'prospect', NULL, '2026-08-26T06:16:51.145', 'kw srishti|raj nagar extension ghaziabad') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-galaxy-north-avenue-ii', 'Galaxy North Avenue-II', NULL, 'Greater Noida West', NULL, NULL, 'prospect', NULL, '2026-08-26T10:17:00.695', 'galaxy north avenue ii|greater noida west') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-ace-city', 'Ace City', '2508', 'GH-01, Sector 1, Greater Noida West, Gautam Buddha Nagar, UP 201306', NULL, NULL, 'active', NULL, '2026-08-26T06:16:51.145', 'ace city|gh 01 sector 1 greater noida west gautam buddha nagar up 201306') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-ace-aspire', 'Ace Aspire', '1265', 'Atul Marg, Techzone 4, Amrapali Leisure Valley, Greater Noida 201318, Uttar Pradesh', NULL, NULL, 'active', NULL, '2026-08-26T06:16:51.145', 'ace aspire|atul marg techzone 4 amrapali leisure valley greater noida 201318 uttar pradesh') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-aditya-mega-city', 'Aditya Mega City', '605', 'Plot No 3, Vaibhav Khand, Indirapuram, Ghaziabad 201014, Uttar Pradesh', NULL, NULL, 'active', NULL, '2026-08-26T06:16:51.145', 'aditya mega city|plot no 3 vaibhav khand indirapuram ghaziabad 201014 uttar pradesh') ON CONFLICT (id) DO NOTHING;
INSERT INTO societies (id, name, flat_count, location, latitude, longitude, status, next_election_date, created_at, dedupe_key) VALUES ('soc-aditya-urban-casa', 'Aditya Urban Casa', '736', 'Sector 78, Noida', NULL, NULL, 'active', NULL, '2026-08-26T06:16:51.145', 'aditya urban casa|sector 78 noida') ON CONFLICT (id) DO NOTHING;
