-- Societies commissioned before this system existed: Gaur Saundaryam.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "Gaur Saundaryam"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ Gaur Saundaryam ═════════════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-gaur-saundaryam-contract';
DELETE FROM contracts   WHERE id = 'bf-gaur-saundaryam-contract';
DELETE FROM agreements  WHERE id = 'bf-gaur-saundaryam-agreement';
DELETE FROM offers      WHERE id = 'bf-gaur-saundaryam-offer';
DELETE FROM demo_reports WHERE id = 'bf-gaur-saundaryam-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-gaur-saundaryam-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-gaur-saundaryam-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-gaur-saundaryam-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-gaur-saundaryam-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-gaur-saundaryam-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-gaur-saundaryam-survey';
DELETE FROM pipelines   WHERE id = 'bf-gaur-saundaryam-pipe';
DELETE FROM engagements WHERE id = 'bf-gaur-saundaryam-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'Gaur Saundaryam';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'Gaur Saundaryam'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'Gaur Saundaryam'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'Gaur Saundaryam';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-gaur-saundaryam-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'Gaur Saundaryam' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-gaur-saundaryam-pipe', s.id, 'lighting', 'active_billing',
       'Gaur Saundaryam', NULL, '2026-02-21'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'Gaur Saundaryam' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-gaur-saundaryam-survey', 'bf-gaur-saundaryam-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-gaur-saundaryam-ckt-1', s.id, 'bf-gaur-saundaryam-survey', 'lighting', 'basement',
       45, 2362, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2024-12-05'::date, '2024-12-31'::date,
       20.37, 62.43,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.',
                          'deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo", "benchmark-adjusted-for-excluded-devices", "two-versions-of-the-demo-report", "report-contradicts-its-own-table"]'::jsonb,
                          'basisNote', '42 tube lights at 20W and 5 surface lights at 18W, all running 24h; theoretical 22.32 kWh/day against a measured 20.37. TWO of the five surface lights were not replaced, and their theoretical 0.86 kWh/day (2 x 18 x 24 / 1000) comes off both sides - CON-16''s excluded-device rule, by theoretical load, as at Aditya Mega City and Arihant Arden. So 20.37 - 0.86 = 19.51 before and 8.19 - 0.86 = 7.33 after, giving 12.18/19.51 = 62.4295%, the agreed 62.43%. The measured whole-circuit ratio is 59.7938%, which is why the benchmark is an override. TWO VERSIONS OF THIS REPORT EXIST. The copy attached to the SIGNED agreement deducts 0.86 and states 62.43%; another revision deducts 2.16 (all five surface lights) and states 66.88%, and reports the whole-month average as 8.19 where the signed copy says 8.21. The signed copy governs. NOTE: this corrects an earlier reading recorded in PROJECT_CONTEXT, which took all five surface lights as unreplaced and put the circuit at 66.89%. Both versions'' conclusions say ''39 motion-enabled tube lights'' and ''62.60%'', matching neither their own findings (42 tube lights) nor their own savings arithmetic. Both tables reproduce their stated averages: 5 pre days 06-10 Dec 2024 average 20.3680 against 20.37, 11 post days 01-11 Jan 2025 average 8.1882 against 8.19. Neither date is stated: meter install taken as the day before the first pre-install reading (06 Dec 2024), replacement as the day before the post-install readings start (01 Jan 2025).'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Gaur Saundaryam' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-gaur-saundaryam-ckt-1-inv', 'bf-gaur-saundaryam-survey', 'Basement', 'basement',
        2362, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-gaur-saundaryam-ckt-1-dev-1', 'bf-gaur-saundaryam-ckt-1', dt.id, 42, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Surface light 18W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Surface light 18W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-gaur-saundaryam-ckt-1-dev-2', 'bf-gaur-saundaryam-ckt-1', dt.id, 3, 18, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Surface light 18W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Surface light 18W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Surface light 18W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-gaur-saundaryam-ckt-1-dev-3', 'bf-gaur-saundaryam-ckt-1', dt.id, 2, 18, 24,
       true, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Surface light 18W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1', 'bf-gaur-saundaryam-ckt-1', 1, 45,
        20.37, 8.19, 59.7938144329897, false,
        NULL, '5 pre days 06-10 Dec 2024 averaging 20.3680 against a stated 20.37, then 11 days 01-11 Jan 2025 averaging 8.1882 against 8.19. Metered count is the 45 fittings actually replaced - 42 tube plus 3 of the 5 surface lights; the other 2 surface lights are excluded.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-pre-2024-12-06', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2024-12-06'::date, 20.48, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-pre-2024-12-07', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2024-12-07'::date, 19.76, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-pre-2024-12-08', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2024-12-08'::date, 20.5, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-pre-2024-12-09', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2024-12-09'::date, 20.56, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-pre-2024-12-10', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2024-12-10'::date, 20.54, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-01', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-01'::date, 7.86, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-02', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-02'::date, 8.05, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-03', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-03'::date, 8.39, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-04', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-04'::date, 8.5, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-05', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-05'::date, 8.22, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-06', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-06'::date, 8.08, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-07', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-07'::date, 8.4, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-08', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-08'::date, 7.99, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-09', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-09'::date, 8.01, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-10', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-10'::date, 8.33, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-gaur-saundaryam-ckt-1-demo-1-post-2025-01-11', 'bf-gaur-saundaryam-ckt-1-demo-1',
        '2025-01-11'::date, 8.24, 'post') ON CONFLICT DO NOTHING;
UPDATE circuits
   SET benchmark_override_pct = 62.43,
       benchmark_override_reason = 'Agreement states 62.43%; the demos on record give 59.7938%. The agreed figure is what this society is billed against.',
       benchmark_override_by_id = (SELECT a.id FROM admin_users a WHERE a.id = 'sys-data-import'),
       benchmark_override_at = now()
 WHERE id = 'bf-gaur-saundaryam-ckt-1' AND benchmark_override_pct IS NULL;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-gaur-saundaryam-demo-report', 'bf-gaur-saundaryam-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-gaur-saundaryam-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 45, "representedLightCount": 2362, "extrapolationFactor": 52.488889, "preInstallBaseline": 20.37, "postInstallAverage": 8.19, "savedKwhPerDay": 12.18, "benchmarkSavingsPct": 62.43, "projectedSavedKwhPerDay": 667.5007, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2026-02-21'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-gaur-saundaryam-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-gaur-saundaryam-offer', 'bf-gaur-saundaryam-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-gaur-saundaryam-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 45, "representedLightCount": 2362, "benchmarkSavingsPct": 62.43, "preInstallBaseline": 20.37, "projectedSavedKwhPerDay": 12.717}]'::jsonb,
       5, 60, 6.67, 36,
       56652.80, '2026-02-21'::date, a.id,
       '2026-02-21'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'Gaur Saundaryam'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at, deviation_note,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-gaur-saundaryam-agreement', 'bf-gaur-saundaryam-pipe', 'bf-gaur-saundaryam-offer', '2026-02-21'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2026-02-21'::date, '2026-02-21'::date,
       '2026-02-21'::date,
       -- How this deal's figures were arrived at, in the field named for it.
       -- These societies predate the system and share no single method, so
       -- the basis travels with the agreement rather than living in a CSV.
       'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: extrapolation-theoretical. Agreement is a scanned PDF; its Annexure A and clause 6 were read by rendering the pages. Every figure reconciles to the paisa: 2,000 x 20W x 24h x 30 = 28,800 kWh/month, 62.43% of it is 17,979.84 kWh at Rs 6.67 = Rs 119,925.53, split 60/40 for FirsThing''s Rs 47,970.21. Its ''Devices & Hardware Rs 40,500 + Service Charges Rs 7,470.21'' is a presentational split of that same 40%, marked ''For Billing Purposes Use Only'', so this is a plain revenue share, not a device charge plus a cut. 2,362 lights installed against a 2,000 minimum, so the agreement''s ''increase proportionately'' clause applied and was honoured: the first invoice bills 2,362 x Rs 10.125 for 15 days, which is the annexure''s own Rs 20.25/light (40,500/2000) halved, and a full month comes to Rs 56,652.80 = Rs 47,970.21 x 2362/2000. Billing from 16 Apr 2026 - the first invoice covers 15 days of a 30-day April - so installation finished on or before 15 Apr (the user). Notarised and signed 21 Feb 2026. Tolerance +/-5%, stated in clause 6.',
       'Documents/Gaur_Saundaryam/2026-02/Agreements/Gaur_Saundaryam_Agreement_2026-02-21.pdf',
       'Gaur_Saundaryam_Agreement_2026-02-21.pdf',
       -- The scan reaches us the day after signing.
       ('2026-02-21'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-gaur-saundaryam-contract', 'bf-gaur-saundaryam-pipe', s.id, 'lighting', 'bf-gaur-saundaryam-agreement', 'active',
       '2026-04-16'::date, ('2026-04-16'::date + '36 months'::interval),
       '2026-04-16'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Gaur Saundaryam' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-gaur-saundaryam-terms', 'bf-gaur-saundaryam-contract', 1, '2026-04-16'::date, 'negotiated_fixed',
       5, 60, 6.67,
       '[{"circuitId": "bf-gaur-saundaryam-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 45, "representedLightCount": 2362, "benchmarkSavingsPct": 62.43, "preInstallBaseline": 20.37, "projectedSavedKwhPerDay": 12.717}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
