-- Societies commissioned before this system existed: The Hyde Park.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "The Hyde Park"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ The Hyde Park ═══════════════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-the-hyde-park-contract';
DELETE FROM contracts   WHERE id = 'bf-the-hyde-park-contract';
DELETE FROM agreements  WHERE id = 'bf-the-hyde-park-agreement';
DELETE FROM offers      WHERE id = 'bf-the-hyde-park-offer';
DELETE FROM demo_reports WHERE id = 'bf-the-hyde-park-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-the-hyde-park-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-the-hyde-park-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-the-hyde-park-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-the-hyde-park-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-the-hyde-park-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-the-hyde-park-survey';
DELETE FROM pipelines   WHERE id = 'bf-the-hyde-park-pipe';
DELETE FROM engagements WHERE id = 'bf-the-hyde-park-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'The Hyde Park';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'The Hyde Park'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'The Hyde Park'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'The Hyde Park';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-the-hyde-park-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'The Hyde Park' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-the-hyde-park-pipe', s.id, 'lighting', 'active_billing',
       'The Hyde Park', NULL, '2025-06-07'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'The Hyde Park' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-the-hyde-park-survey', 'bf-the-hyde-park-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-the-hyde-park-ckt-1', s.id, 'bf-the-hyde-park-survey', 'lighting', 'basement',
       55, 1600, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2025-03-03'::date, '2025-03-23'::date,
       28.66, 64.47,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.',
                          'deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo", "benchmark-adjusted-for-excluded-devices", "excluded-share-prorated-from-measured", "report-contradicts-its-own-table", "represented-count-mixes-fixture-types"]'::jsonb,
                          'basisNote', '63 tube lights on the circuit, of which 55 were replaced and 8 were not. THE EXCLUDED SHARE IS DEDUCTED PRO-RATA FROM THE MEASURED TOTAL, not by theoretical load: the report takes (28.66/63) x 8 = 3.64 kWh/day off, where Aditya Mega City and Arihant Arden both deduct count x wattage x hours. Different method, same intent. So the 55 lights'' figures are 25.02 before and 12.53 - 3.64 = 8.89 after, giving 16.13/25.02 = 64.4684% - the agreed 64.47%. baseline/after recorded here are the MEASURED whole-circuit totals 28.66 and 12.53, which ratio to 56.2805%, so the benchmark is an override. Same treatment as Aditya Mega City. Its post table''s own savings column (57.85, 57.54, 55.95, 56.91, 53.05) averages 56.26%, not the 64.47% printed in its Average cell - the column is against all 63 lights and the average is on the 55-light basis. Both tables reproduce their stated averages: 6 pre days 04-09 Mar 2025 average 28.6633 against 28.66, 5 post days 24-28 Mar average 12.5260 against 12.53. Neither date is stated: meter install taken as the day before the first pre-install reading (04 Mar 2025), replacement as the day before the post-install readings start (24 Mar).'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'The Hyde Park' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-the-hyde-park-ckt-1-inv', 'bf-the-hyde-park-survey', 'Basement', 'basement',
        1600, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-the-hyde-park-ckt-1-dev-1', 'bf-the-hyde-park-ckt-1', dt.id, 55, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-the-hyde-park-ckt-1-dev-2', 'bf-the-hyde-park-ckt-1', dt.id, 8, 20, 24,
       true, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-the-hyde-park-ckt-1-demo-1', 'bf-the-hyde-park-ckt-1', 1, 55,
        28.66, 12.53, 56.28053035589673, false,
        NULL, '6 pre days 04-09 Mar 2025 averaging 28.6633 against a stated 28.66, then 5 days 24-28 Mar averaging 12.5260 against 12.53. Figures are the whole 63-light circuit; the 55-light basis the benchmark uses is 25.02 and 8.89.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-pre-2025-03-04', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-04'::date, 28.77, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-pre-2025-03-05', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-05'::date, 28.8, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-pre-2025-03-06', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-06'::date, 28.73, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-pre-2025-03-07', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-07'::date, 28.38, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-pre-2025-03-08', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-08'::date, 28.78, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-pre-2025-03-09', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-09'::date, 28.52, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-post-2025-03-24', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-24'::date, 12.14, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-post-2025-03-25', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-25'::date, 12.2, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-post-2025-03-26', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-26'::date, 12.5, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-post-2025-03-27', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-27'::date, 12.4, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-the-hyde-park-ckt-1-demo-1-post-2025-03-28', 'bf-the-hyde-park-ckt-1-demo-1',
        '2025-03-28'::date, 13.39, 'post') ON CONFLICT DO NOTHING;
UPDATE circuits
   SET benchmark_override_pct = 64.47,
       benchmark_override_reason = 'Agreement states 64.47%; the demos on record give 56.2805%. The agreed figure is what this society is billed against.',
       benchmark_override_by_id = (SELECT a.id FROM admin_users a WHERE a.id = 'sys-data-import'),
       benchmark_override_at = now()
 WHERE id = 'bf-the-hyde-park-ckt-1' AND benchmark_override_pct IS NULL;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-the-hyde-park-demo-report', 'bf-the-hyde-park-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-the-hyde-park-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 55, "representedLightCount": 1600, "extrapolationFactor": 29.090909, "preInstallBaseline": 28.66, "postInstallAverage": 12.53, "savedKwhPerDay": 16.13, "benchmarkSavingsPct": 64.47, "projectedSavedKwhPerDay": 537.5157, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2025-06-07'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-the-hyde-park-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-the-hyde-park-offer', 'bf-the-hyde-park-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-the-hyde-park-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 55, "representedLightCount": 1600, "benchmarkSavingsPct": 64.47, "preInstallBaseline": 28.66, "projectedSavedKwhPerDay": 18.4771}]'::jsonb,
       10, 65.6168, 6.90, 36,
       32500.00, '2025-06-07'::date, a.id,
       '2025-06-07'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'The Hyde Park'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at, deviation_note,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-the-hyde-park-agreement', 'bf-the-hyde-park-pipe', 'bf-the-hyde-park-offer', '2025-06-07'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2025-06-07'::date, '2025-06-07'::date,
       '2025-06-07'::date,
       -- How this deal's figures were arrived at, in the field named for it.
       -- These societies predate the system and share no single method, so
       -- the basis travels with the agreement rather than living in a CSV.
       'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: extrapolation-theoretical, fee-flat-monthly-charge, report-share-differs-from-agreement, proration-on-a-30-day-month. SOURCE IS THE USER''S PASTED TEXT for the agreement and demo report; the first invoice is a real file. Every figure reconciles: 1,600 x 20W x 24h x 30 = 23,040 kWh/month, less a stated 9,341 post-installation, gives 13,699 kWh saved at Rs 6.90 = Rs 94,523, less the flat Rs 32,500 charge = Rs 62,023 retained, all as printed. FEE IS A FLAT Rs 32,500/month, not a share; the 65.6168/34.3832 split recorded is what that amount works out to. The agreement calls it ''approximately 35% + charges of Inverter lights & installation''; the demo report''s own ''40% of these verified savings'' matches neither. 1,600 lights agreed and 1,600 installed, but they are NOT one kind of fitting: 1,475 motion-sensor dimmable and 125 inverter tube lights that stay on at full brightness for emergency lighting. The demo covered motion-sensor lights only, so it does not represent all 1,600 equally. Billing from 6 Jul 2025: the first invoice covers 26 days of July, and it prorates on a THIRTY-day month - Rs 32,500/30 = Rs 1,083.33/day x 26 = Rs 28,166.58 - not on July''s actual 31. So installation finished on or before 5 Jul 2025. Agreement notarised and signed 07 Jun 2025; its own effective date is 01 Jul 2025.',
       'Documents/The_Hyde_Park/2025-06/Agreements/The_Hyde_Park_Agreement_2025-06-07.pdf',
       'The_Hyde_Park_Agreement_2025-06-07.pdf',
       -- The scan reaches us the day after signing.
       ('2025-06-07'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-the-hyde-park-contract', 'bf-the-hyde-park-pipe', s.id, 'lighting', 'bf-the-hyde-park-agreement', 'active',
       '2025-07-06'::date, ('2025-07-06'::date + '36 months'::interval),
       '2025-07-06'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'The Hyde Park' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-the-hyde-park-terms', 'bf-the-hyde-park-contract', 1, '2025-07-06'::date, 'negotiated_fixed',
       10, 65.6168, 6.90,
       '[{"circuitId": "bf-the-hyde-park-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 55, "representedLightCount": 1600, "benchmarkSavingsPct": 64.47, "preInstallBaseline": 28.66, "projectedSavedKwhPerDay": 18.4771}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
