-- How each pre-system society's figures were arrived at.
--
-- These eight were commissioned before this system existed and there was no
-- single method between them: one agreement extrapolates the demo's MEASURED
-- daily figure to the contracted count, the next uses the theoretical; one
-- averages two demos' percentages, another was billed on an annexure that
-- says outright it would be revised and never was; one starts billing the day
-- after installation completes, another the same day.
--
-- None of it can be corrected — it is what was signed and what these
-- societies have been billed on — so it is recorded instead, against the rows
-- the figures live on rather than in a spreadsheet nobody opens. A number
-- whose basis is unstated cannot be defended when it is questioned, which is
-- what INV-02 exists to prevent. New deals follow one method; these carry
-- their own, in writing, wherever the figure is shown.
--
-- Written by scripts/make-data-migrations.py from docs/backfill/*.csv, and
-- generated inline for every society imported after this one. Guarded so it
-- only ever fills a record that is still absent.

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "represented-count-from-invoice", "benchmark-single-demo", "benchmark-rounded-in-agreement"]'::jsonb, 'basisNote', 'Report''s own tables average to 48.6987 and 16.3629 -> 66.3998%, matching its stated figures exactly. Neither date is stated: meter-install taken as the day before its first reading (03 Aug), replacement as the day before the post-install readings start (16 Oct). NOTE - the meter workbook for this circuit shows consumption dropping from ~48 to ~18 kWh/day on 18 Aug 2025, so the lights were physically changed then; the report simply re-measured in October. Represented count is the first invoice''s own figure ("Number of lights = 2,508"), which the agreement rounds to 2,500.')
 WHERE id = 'bf-ace-city-ckt-1' AND NOT (eligibility_checklist ? 'deviations');

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo"]'::jsonb, 'basisNote', 'Report''s own tables average to 32.9073 (11 days, 19/02-01/03) and 12.2570 (10 days, 03/03-12/03) -> 62.75%, against its stated 32.91 / 12.25 / 62.78%. Its pre-install header says ''19 Feb - 22 Feb 2026'' while the table runs to 01/03; the table is what reproduces the stated average. Neither date is stated: meter-install taken as the day before the first reading, replacement as the day before the post-install readings start. Represented count is the first invoice''s Qty (1,265). Report does not name the area or the running hours. Area is not named in the report; taken as basement because the circuit runs 24h (71 x 20W x 24h = 34.08 kWh/day against a measured 32.91, 3.6% off) and CON-11 names basement parking as the 24h operating profile - a staircase or external circuit would be dusk-to-dawn.')
 WHERE id = 'bf-ace-aspire-ckt-1' AND NOT (eligibility_checklist ? 'deviations');

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo", "benchmark-adjusted-for-excluded-devices"]'::jsonb, 'basisNote', 'Savings is the AGREEMENT''s 64% benchmark, per the rule. The report prints 63.17%, which its own tables do not give: 8 days 29 Jan-05 Feb average 47.3987 and 7 days 13-19 Feb average 19.6814, which is 58.48% raw or 64.16% once the excluded street lights'' 4.20 kWh/day comes off both sides. The agreement''s Annexure 1 repeats the report''s 63.17% while its body says 64%. Light count is 91, not the 93 the report''s prose states - its own theoretical line of 43.68 kWh/day is 91 x 20W x 24h. Dates are not stated: meter-install taken as the day before the first reading, replacement as the day before the after-readings start. Represented count is the invoice''s 605 lights installed.')
 WHERE id = 'bf-aditya-mega-city-ckt-1' AND NOT (eligibility_checklist ? 'deviations');

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-mean-of-demo-percentages", "report-contradicts-its-own-table"]'::jsonb, 'basisNote', 'TWO demos on this circuit, averaged - the case the user described. Demo-1: 100 lights, 47.43 -> 24.53 = 48.28%. Demo-2: 22 lights, 12.49 -> 1.85 = 85.19%. The report and the agreement both take the SIMPLE average of the two percentages, 66.72%, not the consumption-weighted 55.97%. Recorded as one circuit of 122 metered lights because that is what reproduces the agreement''s own savings figure. baseline/after are the two demos summed, so they give 55.97% rather than the 66.72% benchmark - that gap is the averaging method, not an error. Dates from the earlier of the two demos.')
 WHERE id = 'bf-aditya-urban-casa-ckt-1' AND NOT (eligibility_checklist ? 'deviations');

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo", "not-billing"]'::jsonb, 'basisNote', 'NOT BILLING YET (the user, 2026-08-26) - commissioned but no fee line. 16 surface lights at 9W running 12h; theoretical 1.73 kWh/day against a measured 1.81. Report: 15 days 24 Apr-08 May 2026 averaging 1.81, then 6 days 11-16 May averaging 0.40, giving 77.9% which it rounds to ~78%; its own agreement states 78%. That agreement states a 57/43 split, a Rs 1,000 fee and 1,153 contracted lights - none of it used while billing has not started. REPRESENTED COUNT UNKNOWN. Represented count 1,153 - its own agreement''s contracted figure, confirmed by the user (2026-08-27). The rest of that agreement''s terms (57/43, a Rs 1,000 fee) stay unused while this circuit is not billing.')
 WHERE id = 'bf-aditya-urban-casa-ckt-2' AND NOT (eligibility_checklist ? 'deviations');

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "demos-run-in-batches", "benchmark-from-superseded-annexure", "report-contradicts-its-own-table"]'::jsonb, 'basisNote', 'TWO demos on this circuit, run a month apart rather than side by side: 40 lights (21-26 Dec 2025 pre, 29 Dec-02 Jan post) then 100 lights (14-29 Jan 2026 pre, 09-16 Feb post). baseline/after are the report''s own combined totals, 19.14+47.17 and 6.68+18.53, which ratio to 61.98% - the report''s own combined figure. The recorded 65.09% is the agreement''s, and is an override for that reason. Meter install taken as the day before the FIRST demo''s first reading; replacement as the day before the SECOND demo''s post-install readings, since that batch completed the circuit. The second demo''s post-install table averages 18.7675 against its own stated 18.53, and 18.53 is what the report''s 60.72% and everything after it were computed from, so 18.53 is what is recorded.')
 WHERE id = 'bf-amrapali-princely-estate-ckt-1' AND NOT (eligibility_checklist ? 'deviations');

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo", "benchmark-adjusted-for-excluded-devices"]'::jsonb, 'basisNote', 'CON-16''s exclusion case, stated outright by the report: 44 tube lights (20W, 24h) share the circuit with 9 ramp lights (12W, 12h) that are not replaced. Its own words - ''We are using 21.24 kWh/day instead of 22.54 kWh/day because the originally recorded consumption included 1.30 kWh/day from 9 ramp lights ... which are not part of our motion-enabled lighting solution.'' The ramp lights'' 1.30 comes off both sides, so 13.62/21.24 = 64.1243% against a raw 60.4259%; the recorded 64.12% is therefore an override. baseline/after are the measured totals, 22.54 and 8.92, both reproduced by the report''s own tables to 4 places (22.5388 and 8.9233). Neither date is stated: meter install taken as the day before the first pre-install reading (15 Jul 2025), replacement as the day before the post-install readings start (24 Jul).')
 WHERE id = 'bf-arihant-arden-ckt-1' AND NOT (eligibility_checklist ? 'deviations');

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo", "benchmark-rounded-in-agreement"]'::jsonb, 'basisNote', '40 tube lights at 20W running 24h; theoretical 19.20 kWh/day against a measured 18.71. The recorded 64.43% is the agreement''s and the report''s own stated figure, and is an override: the arithmetic it prints beside it, (18.71-6.66)/18.71, gives 64.4041%, and the unrounded daily means give 64.4198%. The gap is a rounding slip in the report, not a different measurement. The PDF of this report has no extractable text and was first read by rendering it through CoreGraphics; a readable .docx was supplied afterwards and the parser''s rows match that reading exactly, so the figures are parsed rather than transcribed. Both tables'' means reproduce the report''s own stated averages - 5 pre days average 18.7140 against 18.71, 4 post days average 6.6575 against 6.66. Neither date is stated: meter install taken as the day before the first pre-install reading (07 Jan 2026), replacement as the day before the post-install readings start (18 Jan).')
 WHERE id = 'bf-ats-greens-paradiso-ckt-1' AND NOT (eligibility_checklist ? 'deviations');

UPDATE circuits SET eligibility_checklist = eligibility_checklist
  || jsonb_build_object('deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-single-demo"]'::jsonb, 'basisNote', '47 tube lights at 20W running 24h; theoretical 22.56 kWh/day against a measured 23.80, a +5.49% variance the report itself records as within range. NO OVERRIDE: the raw demo arithmetic gives (23.80-7.83)/23.80 = 67.1008%, which is the agreed 67.10% to two places - the first of these societies where the measured figure and the contracted one agree without one. Both tables reproduce their stated averages: 6 pre days 14-19 Sep 2025 average 23.7983 against a stated 23.80, 7 post days 23-29 Sep average 7.8314 against 7.83. Neither date is stated: meter install taken as the day before the first pre-install reading (14 Sep 2025), replacement as the day before the post-install readings start (23 Sep).')
 WHERE id = 'bf-bestech-park-view-residency-ckt-1' AND NOT (eligibility_checklist ? 'deviations');

UPDATE agreements SET deviation_note = 'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Named in the agreement as "Ace City Apartment Owners Association". Share computed from its own figures: Rs 54214 of Rs 150595 = 36.00% FirsThing / 64.00% society, matching the stated ~36%. Tolerance is the 10% default - the agreement states none. Phone redacted in the scan (98******59). Signed date is the page-1 effective date; the stamp reads 10/11/2025, the customer signature 11/10/25, the notary 10 Nov 2025. Term start is the installation-completion date, derived from the first invoice (INV80850028, issued 31/12/2025): it bills 16 days of a 31-day December, so billing ran 16-31 Dec and completion was 15 Dec 2025. Address is the invoice''s billing address, printed as "GH-01, SECTOR-01, GREATER NOIDA WEST, Gautambuddha Nagar, Greater Noida, Uttar Pradesh-201306"; case normalised. Society GSTIN 09AANAA9463D1ZG is on the invoice but has no column to live in. Printed and notarised 10 Nov 2025 - the e-stamp certificate date, corroborated by the notary''s own ''10 NOV 2025''. It falls AFTER the 23 Oct front-page effective date, which is normal for a backdated effective date but does mean printed/notarised reads later than signed.'
 WHERE id = 'bf-ace-city-agreement' AND deviation_note IS NULL;

UPDATE agreements SET deviation_note = 'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Agreement states the split outright (Annexure A: FirsThing 42% / society 58%) and the money agrees - Rs 23,920 of Rs 56,954 is 42.00%. Page 5''s ''50% of these verified savings'' contradicts both and is disregarded. Tolerance +/-10% is stated in the agreement itself. Two dates: page 1 says 18 March 2026, the stamp and execution page say 01/04/2026; the first invoice independently cites ''agreement dated 18.03.2026'', so the front-page date stands. Term start from the first invoice: it bills ''for the month of May 2026 - From 25th May'', so installation completed 24 May 2026. Contracted for a ''minimum of 1000 lights''; 1,265 were billed. Contact signed as President/Secretary with no printed name; phone redacted in the scan. Printed and notarised 1 Apr 2026 - the stamp paper and execution date on page 6. Later than the 18 Mar front-page date, same backdated-effective-date pattern as Ace City.'
 WHERE id = 'bf-ace-aspire-agreement' AND deviation_note IS NULL;

UPDATE agreements SET deviation_note = 'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Society is ''ASSOCIATION ADITYA MEGA CITY RESIDENTS WELFARE''; GSTIN 09AACAA5319H2ZV on the invoice. Term start corroborated two ways: the invoice bills 29 days of a 30-day September, so billing ran 2-30 Sept and completion was 1 Sept; and the agreement says installation begins 10 days after the 17 Aug signing. Tolerance is the 10% default - not stated. WATCH: the agreement is not internally consistent on the fee. Rs 13,934 is 27% of the Rs 51,610 it calls the monthly savings, not the 36% it states; the society''s retained Rs 33,030 IS 64% of 51,610. The fee itself is right - it fits 600 lights at the measured saving (Rs 13,817 computed) and matches the first invoice''s Rs 13,581.57 for 29 days. So Rs 51,610 is the figure that does not reconcile. Also note agreed savings and society share are both 64% - separate figures that happen to coincide. Printed and notarised 17 Aug 2025 - the certificate issued date, the same day the agreement itself is dated.'
 WHERE id = 'bf-aditya-mega-city-agreement' AND deviation_note IS NULL;

UPDATE agreements SET deviation_note = 'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: agreement-figures-do-not-reconcile. TWO circuits: basement (billing) and lift lobby (commissioned, NOT billing yet). Share derived from the billed amount, per the user: Rs 23,299 against the basement''s own extrapolation at 736 lights (Rs 50,648/month) is 46.0015% to FirsThing - 46% to a rupee - so 54% to the society. The agreement''s own figures do NOT reconcile and are not used: it states a 20/80 split, a fee of Rs 29,400 and monthly savings of Rs 64,001, the last of which only reproduces at 930 lights rather than 736. Tolerance is +/-5%, stated in the agreement - the first society not on the 10% default. Location left blank: the invoice''s billing address is malformed (''Noida, Uttar Pradesh, noida, , Uttar Pradesh, India'') and adds nothing to the existing ''Sector 78, Noida''. Term start 7 Feb 2026, given by the user (2026-08-27). Not derivable from the invoices supplied: the run opens with a Feb-2026 invoice for the devices (700 at Rs 20 plus a service fee) and the first SAVINGS invoice is March-2026 at Rs 23,299, already a full month - so no partial February savings invoice appears in what was shared, even though completion on 7 Feb implies one. Printed and notarised 4 Jan 2026 - certificate issued date, same day as the agreement.'
 WHERE id = 'bf-aditya-urban-casa-agreement' AND deviation_note IS NULL;

UPDATE agreements SET deviation_note = 'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: fee-device-charge-plus-share-of-net, report-share-differs-from-agreement. Two demos on one basement circuit, 40 lights then 100, in one combined document. BENCHMARK IS 65.09%, NOT the combined report''s 61.98%. The annexure fixed the benchmark on the 40-light demo alone and says in terms ''a demo of 100 lights is currently in progress. We will average the results from both demos and update this annexure after the second report is generated'' - it was never updated, and the invoice proves billing follows the un-updated figure: 2,310 lights at 65.09% and Rs 6.65/kWh reproduce the invoice''s Rs 51,436.00 device line and Rs 11,105.71 service line TO THE PAISA, where 61.98% would give Rs 10,280.07. COMMERCIAL STRUCTURE IS UNLIKE THE OTHERS: a fixed device charge (Rs 66,800/month at 3,000 lights) plus 88/12 of what is left, not a straight share of savings. Both halves scale linearly with the light count, so it reduces to a constant 43.4368% to FirsThing - 56.5632% to the society - which is what is recorded here. Monthly fee is the invoice''s own ex-GST subtotal for 2,310 lights. Signed 26 Feb 2026 by the society; FirsThing signed 02 Feb; stamped and notarised 11 Feb (the user, 2026-08-28). Term start 2 Apr 2026: the first invoice covers 29 days of April, so billing began on the 2nd (the user). Tolerance not stated in the agreement, so the 10% default. 2,310 lights installed against the agreement''s 3,000 minimum; its clause ''valid only if at least 3000 lights are installed'' was not enforced - the invoice bills the 2,310 pro-rata instead.'
 WHERE id = 'bf-amrapali-princely-estate-agreement' AND deviation_note IS NULL;

UPDATE agreements SET deviation_note = 'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: fee-device-charge-plus-share-of-net, report-share-differs-from-agreement. One circuit, one demo. Every figure in the agreement reconciles exactly: 64.12% of 10,800 kWh/month (750 lights x 20W x 24h x 30) = 6,925 kWh at Rs 6.30 = Rs 43,627, less the Rs 14,000 service charge = Rs 29,627 retained by the society, all as printed. The January 2026 invoice bills 750 lights at Rs 18.67 each = Rs 14,001.00 ex-GST (Rs 16,521 with 18% IGST), so exactly the contracted minimum was installed and the charge is flat monthly, not day-prorated - it reads ''For 30 days'' on a 31-day month. Share is derived from what is billed: Rs 14,001 of Rs 43,627 is 32.0925% to FirsThing, 67.9075% to the society. The demo report''s own ''40% of these verified savings will be shared with our company'' does NOT match the agreement''s own arithmetic and is not used. Agreement created and signed 27 Nov 2025 (the user, 2026-08-28); billing starts 1 Jan 2026, so installation finished on or before 31 Dec 2025. Tolerance not stated in the agreement, so the 10% default. Beyond 750 lights the charge rises by Rs 20 + GST per light, which does not apply here.'
 WHERE id = 'bf-arihant-arden-agreement' AND deviation_note IS NULL;

UPDATE agreements SET deviation_note = 'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: extrapolation-measured. One circuit, one demo of 40 lights. Every figure reconciles: the agreement''s 14,032.5 kWh/month is the demo''s MEASURED 18.71 kWh/day extrapolated to 1,000 lights (18.71/40 x 1000 x 30) - CON-11''s own extrapolation, not a theoretical - and 64.43% of it at Rs 6.30 gives Rs 56,953, split 60/40 for FirsThing''s Rs 22,781. The agreement is written for an ESTIMATED 1,000 lights and says the invoice adjusts to the actual installed count; 951 went in (the user, 2026-08-28), and the June 2026 invoice bills 951 x Rs 22.78 = Rs 21,663.78 ex-GST, which is Rs 22,781/1000 per light. It cites ''agreement dated 17.03.2026'', matching the notarisation date. TOLERANCE IS +/-5%, stated in the agreement (''an acceptable variance of +/-5% in energy reduction'') - the second society not on the 10% default, after Aditya Urban Casa. Notarised 17 Mar 2026, signed 22 Mar 2026, billing from 1 Jun 2026 so installation finished on or before 31 May (all from the user). The demo report''s own ''40% of these verified savings will be shared with our company'' agrees with the agreement''s 60/40 split.'
 WHERE id = 'bf-ats-greens-paradiso-agreement' AND deviation_note IS NULL;

UPDATE agreements SET deviation_note = 'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: extrapolation-theoretical, fee-device-charge-plus-share-of-net, billing-starts-on-completion-day, report-share-differs-from-agreement. SOURCE IS THE USER''S PASTED TEXT (2026-08-28), not a file on disk - both the agreement and the demo report were supplied inline, so the readings below are transcribed from that text rather than parsed from a document. Every figure was checked against the documents'' own arithmetic and all of it reconciles exactly. Agreement made 07 Oct 2025, notarised and signed the same day 05 Feb 2026; billing from 15 Mar 2026: the first invoice was raised on 31 Mar 2026 for 17 days, and 17 days ending the 31st can only start on the 15th. Installation finished ON 15 Mar (the user, 2026-08-28), so billing began the SAME day it completed rather than the day after - a departure from CON-22''s normal rule, and the reason this contract''s term starts on the 15th rather than the 16th. Nothing here stores a completion date for CON-22 to derive from; term_start is taken as given. That first invoice is therefore prorated to Rs 6,546.65 ex-GST; the Rs 11,938 recorded here is the full monthly charge the contract runs at, which CON-22 prorates for the opening month. 400 lights agreed and 400 installed, so no additional-light charge applies. PRE-INSTALLATION CONSUMPTION IS THE THEORETICAL, NOT THE MEASURED, unlike ATS Greens Paradiso: 5,760 kWh/month is 400 x 20W x 24h x 30, where extrapolating the demo''s measured 23.80 kWh/day over 47 lights would give 6,076.6. The agreement took the lower figure, and every downstream number follows from it: 67.10% of 5,760 = 3,865 kWh at Rs 6.50 = Rs 25,122, less Rs 8,000 for hardware = Rs 17,122 net, of which FirsThing takes 23% = Rs 3,938, for a monthly payable of Rs 11,938 + GST. The structure is a fixed device charge plus a share of what remains, as at Amrapali Princely Estate, and reduces to a constant 47.5201% to FirsThing - 52.4799% to the society. Tolerance +/-10%, stated in the agreement''s clause 18 rather than defaulted. The demo report''s own ''50% of these verified savings'' does not match the agreement and is not used.'
 WHERE id = 'bf-bestech-park-view-residency-agreement' AND deviation_note IS NULL;
