-- Societies commissioned before this system existed: RG Residency.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "RG Residency"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ RG Residency ════════════════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-rg-residency-contract';
DELETE FROM contracts   WHERE id = 'bf-rg-residency-contract';
DELETE FROM agreements  WHERE id = 'bf-rg-residency-agreement';
DELETE FROM offers      WHERE id = 'bf-rg-residency-offer';
DELETE FROM demo_reports WHERE id = 'bf-rg-residency-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-rg-residency-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-rg-residency-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-rg-residency-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-rg-residency-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-rg-residency-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-rg-residency-survey';
DELETE FROM pipelines   WHERE id = 'bf-rg-residency-pipe';
DELETE FROM engagements WHERE id = 'bf-rg-residency-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'RG Residency';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'RG Residency'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'RG Residency'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'RG Residency';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-rg-residency-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'RG Residency' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-rg-residency-pipe', s.id, 'lighting', 'active_billing',
       'RG Residency', NULL, '2025-11-08'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'RG Residency' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-rg-residency-survey', 'bf-rg-residency-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-rg-residency-ckt-1', s.id, 'bf-rg-residency-survey', 'lighting', 'basement',
       69, 1444, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2025-09-06'::date, '2025-10-04'::date,
       32.69, 66.00,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.',
                          'deviations', '["eligibility-never-assessed", "dates-inferred-from-readings", "benchmark-mean-of-demo-percentages", "benchmark-rounded-in-agreement", "report-dates-contradict-its-tables"]'::jsonb,
                          'basisNote', 'TWO demos on two areas, both recorded against this one circuit because the agreement prices them as one: 49 stilt lights (22.67 -> 10.49 = 53.75%) and 20 basement lights (10.02 -> 2.13 = 78.75%). Their simple mean is 66.25%; the agreement''s own arithmetic gives 66.00%, so the benchmark is an override of a rounded figure. The consumption-weighted ratio would be 61.39% and is not used - same mean-of-percentages rule as Aditya Urban Casa. baseline/after are the two demos summed, 32.69 and 12.62. BOTH REPORTS'' PROSE CONTRADICTS THEIR OWN TABLES: each says the pre-installation window was ''(07-11 Oct 2025)'' while the tables list 22-25 Sep for the stilt demo and 07-11 Sep for the basement one. The tables are the data. Both are also headed ''Savings % w.r.t 20.24 kWh'', the same leftover French Apartment carries; each report''s own percentages only work against its own baseline. The stilt report marks every post-installation day ''Within Acceptable Range: No'' - its 53.75% sits well below the basement demo''s 78.75%, which is what the averaging resolves. All four tables reproduce their stated averages to 2dp. Neither date is stated: meter install taken as the day before the earliest reading of either demo (07 Sep 2025), replacement as the day before the later demo''s post-install readings start (05 Oct).'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'RG Residency' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-rg-residency-ckt-1-inv', 'bf-rg-residency-survey', 'Basement', 'basement',
        1444, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-rg-residency-ckt-1-dev-1', 'bf-rg-residency-ckt-1', dt.id, 69, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-rg-residency-ckt-1-demo-1', 'bf-rg-residency-ckt-1', 1, 49,
        22.67, 10.49, 53.7273930304367, false,
        NULL, 'Stilt area, report dated 16 Oct 2025. 4 pre days 22-25 Sep 2025 averaging 22.6700 against a stated 22.67, then 4 days 05-08 Oct averaging 10.4850 against 10.49. Its report marks every post-installation day out of acceptable range.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-1-pre-2025-09-22', 'bf-rg-residency-ckt-1-demo-1',
        '2025-09-22'::date, 22.41, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-1-pre-2025-09-23', 'bf-rg-residency-ckt-1-demo-1',
        '2025-09-23'::date, 23.18, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-1-pre-2025-09-24', 'bf-rg-residency-ckt-1-demo-1',
        '2025-09-24'::date, 22.92, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-1-pre-2025-09-25', 'bf-rg-residency-ckt-1-demo-1',
        '2025-09-25'::date, 22.17, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-1-post-2025-10-05', 'bf-rg-residency-ckt-1-demo-1',
        '2025-10-05'::date, 10.12, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-1-post-2025-10-06', 'bf-rg-residency-ckt-1-demo-1',
        '2025-10-06'::date, 10.67, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-1-post-2025-10-07', 'bf-rg-residency-ckt-1-demo-1',
        '2025-10-07'::date, 10.61, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-1-post-2025-10-08', 'bf-rg-residency-ckt-1-demo-1',
        '2025-10-08'::date, 10.54, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-rg-residency-ckt-1-demo-2', 'bf-rg-residency-ckt-1', 2, 20,
        10.02, 2.13, 78.74251497005989, false,
        NULL, 'Basement area, report dated 22 Oct 2025. 5 pre days 07-11 Sep 2025 averaging 10.0220 against a stated 10.02, then 7 days 15-21 Sep averaging 2.1300 against 2.13.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-pre-2025-09-07', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-07'::date, 9.97, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-pre-2025-09-08', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-08'::date, 9.9, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-pre-2025-09-09', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-09'::date, 10.08, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-pre-2025-09-10', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-10'::date, 10.08, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-pre-2025-09-11', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-11'::date, 10.08, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-post-2025-09-15', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-15'::date, 2.12, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-post-2025-09-16', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-16'::date, 2.27, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-post-2025-09-17', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-17'::date, 2.31, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-post-2025-09-18', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-18'::date, 2.21, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-post-2025-09-19', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-19'::date, 2.1, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-post-2025-09-20', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-20'::date, 2.01, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-rg-residency-ckt-1-demo-2-post-2025-09-21', 'bf-rg-residency-ckt-1-demo-2',
        '2025-09-21'::date, 1.89, 'post') ON CONFLICT DO NOTHING;
UPDATE circuits
   SET benchmark_override_pct = 66.0,
       benchmark_override_reason = 'Agreement states 66.0%; the demos on record give 66.235%. The agreed figure is what this society is billed against.',
       benchmark_override_by_id = (SELECT a.id FROM admin_users a WHERE a.id = 'sys-data-import'),
       benchmark_override_at = now()
 WHERE id = 'bf-rg-residency-ckt-1' AND benchmark_override_pct IS NULL;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-rg-residency-demo-report', 'bf-rg-residency-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-rg-residency-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 69, "representedLightCount": 1444, "extrapolationFactor": 20.927536, "preInstallBaseline": 32.69, "postInstallAverage": 12.62, "savedKwhPerDay": 20.07, "benchmarkSavingsPct": 66.0, "projectedSavedKwhPerDay": 451.52, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2025-11-08'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-rg-residency-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-rg-residency-offer', 'bf-rg-residency-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-rg-residency-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 69, "representedLightCount": 1444, "benchmarkSavingsPct": 66.0, "preInstallBaseline": 32.69, "projectedSavedKwhPerDay": 21.5754}]'::jsonb,
       5, 55.2044, 8.6267, 36,
       53034.00, '2025-11-08'::date, a.id,
       '2025-11-08'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'RG Residency'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at, deviation_note,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-rg-residency-agreement', 'bf-rg-residency-pipe', 'bf-rg-residency-offer', '2025-11-08'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2025-11-08'::date, '2025-11-08'::date,
       '2025-11-08'::date,
       -- How this deal's figures were arrived at, in the field named for it.
       -- These societies predate the system and share no single method, so
       -- the basis travels with the agreement rather than living in a CSV.
       'Commissioned before this system existed. There was no single method across these societies, so how this deal''s figures were arrived at is recorded here rather than assumed. Departures from the standard: extrapolation-theoretical, fee-device-charge-plus-share-of-net, agreement-figures-do-not-reconcile, report-share-differs-from-agreement. SOURCE IS THE USER''S PASTED TEXT for the agreement and both demo reports; the invoices are real files. THE AGREEMENT''S BENCHMARK GOVERNS, on the user''s instruction (2026-08-28): ''the reports will have inconsistencies with whats in the agreement. so we will consider whatever is given in agreement as bench mark''. Its annexure gives no percentage outright, but its own figures do: 13,020.48 kWh saved of 19,728 = exactly 66.00%, and 19,728 is 1,370 x 20W x 24h x 30, the theoretical. THE AGREEMENT''S COMMERCIAL FIGURES DO NOT REPRODUCE THE INVOICE. Its annexure gives Rs 32,812 devices + Rs 15,902 (20% of the Rs 79,512 net) = Rs 48,714 for 1,370 lights, plus Rs 35 per light beyond that, which for the 1,444 installed would be Rs 51,304. The January 2026 invoice, a full 31 days, bills 1,444 x Rs 20 = Rs 28,880 of devices plus Rs 24,154 of servicing = Rs 53,034. The invoice is what the society pays, so Rs 53,034 is recorded and the share is derived from it: 44.7956% to FirsThing, 55.2044% to the society. Its implied rate is Rs 8.6267/kWh (112,324/13,020.48), higher than any other society here. Billing from 16 Dec 2025 - the first invoice covers 16 days of December - so installation finished on or before 15 Dec. That first invoice also carries a one-off Rs 2,800 Wifi Smart Meter, which is hardware and not part of the monthly charge. Notarised and signed 08 Nov 2025, though the agreement''s own opening line dates it the 6th. Tolerance +/-5%, from the termination clause: savings may vary +/-5%, below which termination is triggered. Both reports'' ''50% of these verified savings'' matches neither the agreement nor the invoice.',
       'Documents/RG_Residency/2025-11/Agreements/RG_Residency_Agreement_2025-11-08.pdf',
       'RG_Residency_Agreement_2025-11-08.pdf',
       -- The scan reaches us the day after signing.
       ('2025-11-08'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-rg-residency-contract', 'bf-rg-residency-pipe', s.id, 'lighting', 'bf-rg-residency-agreement', 'active',
       '2025-12-16'::date, ('2025-12-16'::date + '36 months'::interval),
       '2025-12-16'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'RG Residency' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-rg-residency-terms', 'bf-rg-residency-contract', 1, '2025-12-16'::date, 'negotiated_fixed',
       5, 55.2044, 8.6267,
       '[{"circuitId": "bf-rg-residency-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 69, "representedLightCount": 1444, "benchmarkSavingsPct": 66.0, "preInstallBaseline": 32.69, "projectedSavedKwhPerDay": 21.5754}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
