#!/usr/bin/env python3
"""
The three CSVs -> the SQL that onboards those societies.

    python3 scripts/backfill-sql.py [--only "Ace City,Ace Aspire"] > out.sql

Follows docs/backfill/onboard-society.sql, one transaction per society, and
refuses rather than guesses:

  - the society is found BY NAME and must already exist. These 19 were
    imported with their flat counts and portal accounts; inventing a second
    row keyed on a slug would duplicate them.
  - a blank `term_start` means no contract and no term version. The agreement
    and its offer are still recorded, exactly as the app's own
    startContractTerm path leaves them, and the deal stops at `agreed`
    instead of `active_billing`.
  - a blank `location` leaves the stored address alone.
  - only circuits marked `billing=yes` appear in the contract's benchmark
    table.
"""
import csv, json, re, sys
from datetime import date

ROOT = "docs/backfill"
ACTOR = "yogesh@firsthing.earth"


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def q(value) -> str:
    """A SQL string literal, or NULL."""
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def num(value):
    return "NULL" if value in (None, "") else str(value)


def rows(name: str):
    with open(f"{ROOT}/{name}.csv") as fh:
        return list(csv.DictReader(fh))


def circuit_term(soc_slug: str, i: int, c: dict) -> dict:
    """One entry of offers.circuit_terms / contract_term_versions.circuit_benchmarks."""
    base = float(c["baseline_kwh_day"])
    pct = float(c["savings_pct"])
    return {
        "circuitId": f"bf-{soc_slug}-ckt-{i}",
        "lightType": c["light_type"],
        "location": c["circuit_location"] or None,
        "meteredLightCount": None,      # filled by the caller, which knows the devices
        "representedLightCount": int(c["represented_light_count"]),
        "benchmarkSavingsPct": pct,
        "preInstallBaseline": base,
        "projectedSavedKwhPerDay": round(base * pct / 100, 4),
    }


def main() -> None:
    only = None
    if "--only" in sys.argv:
        only = {s.strip() for s in sys.argv[sys.argv.index("--only") + 1].split(",")}

    societies = rows("societies")
    circuits = rows("circuits")
    devices = rows("circuit_devices")

    print("-- Generated by scripts/backfill-sql.py — do not edit by hand.")
    print(f"-- {date.today().isoformat()}\n")
    print("\\set ON_ERROR_STOP on\n")

    for s in societies:
        name = s["society_name"]
        if only and name not in only:
            continue
        sl = slug(name)
        mine = [c for c in circuits if c["society_name"] == name]
        has_contract = bool(s["term_start"])

        print(f"-- ═══ {name} " + "═" * max(0, 60 - len(name)))
        print("BEGIN;")
        print(f"""
-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = {q(name)};
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', {q(name)}; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, {q(name)}; END IF;
END $$;
""")
        loc = s["location"]
        if loc:
            print(f"""UPDATE societies
   SET status = 'active',
       location = {q(loc)},
       -- dedupe_key is derived from name|location and carries the unique
       -- index; it has to move with the address or it describes the old one.
       dedupe_key = btrim(regexp_replace(lower(name), '[^a-z0-9]+', ' ', 'g'))
                    || '|' || btrim(regexp_replace(lower({q(loc)}), '[^a-z0-9]+', ' ', 'g'))
 WHERE name = {q(name)};""")
        else:
            print(f"UPDATE societies SET status = 'active' WHERE name = {q(name)};   -- address left as stored")

        print(f"""
INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-{sl}-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = {q(name)};

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-{sl}-pipe', s.id, 'lighting', {"'active_billing'" if has_contract else "'agreed'"},
       {q(s['contact_name'] or name)}, {q(s['contact_phone'])}, {q(s['agreement_signed_on'])}::date,
       a.id, a.id, true,
       {q('Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.')},
       now(), now()
FROM societies s, admin_users a WHERE s.name = {q(name)} AND a.email = {q(ACTOR)};

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-{sl}-survey', 'bf-{sl}-pipe', now());""")

        terms = []
        for i, c in enumerate(mine, 1):
            cid = f"bf-{sl}-ckt-{i}"
            lines = [d for d in devices
                     if d["society_name"] == name and d["circuit_location"] == c["circuit_location"]]
            included = [d for d in lines if d["excluded"].lower() != "yes"]
            metered = sum(int(d["count"]) for d in included)
            primary = included[0]
            print(f"""
INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT '{cid}', s.id, 'bf-{sl}-survey', 'lighting', {q(c['light_type'])},
       {metered}, {c['represented_light_count']}, {primary['wattage_each']}, {primary['hours_per_day']},
       'benchmark_confirmed', {q(c['circuit_location'])},
       {q(c['meter_installed_on'])}::date, {q(c['lights_replaced_on'])}::date,
       {c['baseline_kwh_day']}, {c['savings_pct']},
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = {q(name)} AND a.email = {q(ACTOR)};""")
            for j, d in enumerate(lines, 1):
                excl = d["excluded"].lower() == "yes"
                print(f"""INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT '{cid}-dev-{j}', '{cid}', dt.id, {d['count']}, {d['wattage_each']}, {d['hours_per_day']},
       {str(excl).lower()}, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = {q(d['device_name'])} AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.email = {q(ACTOR)};""")
            if c["billing"].lower() == "yes":
                t = circuit_term(sl, i, c)
                t["meteredLightCount"] = metered
                terms.append(t)

        terms_json = json.dumps(terms).replace("'", "''")
        first = mine[0]
        print(f"""
-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-{sl}-demo-report', 'bf-{sl}-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '{terms_json}'::jsonb, now(), {q(s['agreement_signed_on'])}::date, p.id
FROM circuits c
LEFT JOIN profiles p ON p.society_id = c.society_id
     AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE c.id = 'bf-{sl}-ckt-1';

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-{sl}-offer', 'bf-{sl}-pipe', 1, 'accepted', 'negotiated_fixed', '{terms_json}'::jsonb,
       {s['tolerance_pct']}, {s['society_share_pct']}, {s['unit_rate_inr']}, {s['term_months']},
       {num(s['monthly_fee_inr'])}, {q(s['agreement_signed_on'])}::date, a.id,
       {q(s['agreement_signed_on'])}::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = {q(name)}
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.email = {q(ACTOR)};

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id, signed_at)
SELECT 'bf-{sl}-agreement', 'bf-{sl}-pipe', 'bf-{sl}-offer', {q(s['agreement_signed_on'])}::date, a.id,
       {q(s['agreement_signed_on'])}::date
FROM admin_users a WHERE a.email = {q(ACTOR)};""")
        void(first)

        if has_contract:
            print(f"""
INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-{sl}-contract', 'bf-{sl}-pipe', s.id, 'lighting', 'bf-{sl}-agreement', 'active',
       {q(s['term_start'])}::date, ({q(s['term_start'])}::date + '{s['term_months']} months'::interval),
       {q(s['term_start'])}::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = {q(name)} AND a.email = {q(ACTOR)};

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-{sl}-terms', 'bf-{sl}-contract', 1, {q(s['term_start'])}::date, 'negotiated_fixed',
       {s['tolerance_pct']}, {s['society_share_pct']}, {s['unit_rate_inr']},
       '{terms_json}'::jsonb, a.id, now()
FROM admin_users a WHERE a.email = {q(ACTOR)};""")
        else:
            print(f"\n-- No contract: term_start is unknown, so there is nothing to run the term from.")
            print(f"-- The agreement and its offer stand; the deal waits at 'agreed'.")
        print("COMMIT;\n")


def void(_):
    return None


if __name__ == "__main__":
    main()
