-- Societies commissioned before this system existed: Arihant Arden.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "Arihant Arden"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ Arihant Arden ═══════════════════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-arihant-arden-contract';
DELETE FROM contracts   WHERE id = 'bf-arihant-arden-contract';
DELETE FROM agreements  WHERE id = 'bf-arihant-arden-agreement';
DELETE FROM offers      WHERE id = 'bf-arihant-arden-offer';
DELETE FROM demo_reports WHERE id = 'bf-arihant-arden-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-arihant-arden-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-arihant-arden-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-arihant-arden-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-arihant-arden-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-arihant-arden-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-arihant-arden-survey';
DELETE FROM pipelines   WHERE id = 'bf-arihant-arden-pipe';
DELETE FROM engagements WHERE id = 'bf-arihant-arden-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'Arihant Arden';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'Arihant Arden'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'Arihant Arden'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'Arihant Arden';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-arihant-arden-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'Arihant Arden' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-arihant-arden-pipe', s.id, 'lighting', 'active_billing',
       'Arihant Arden', NULL, '2025-11-27'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'Arihant Arden' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-arihant-arden-survey', 'bf-arihant-arden-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-arihant-arden-ckt-1', s.id, 'bf-arihant-arden-survey', 'lighting', 'basement',
       44, 750, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2025-07-14'::date, '2025-07-23'::date,
       22.54, 64.12,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Arihant Arden' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-arihant-arden-ckt-1-inv', 'bf-arihant-arden-survey', 'Basement', 'basement',
        750, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-arihant-arden-ckt-1-dev-1', 'bf-arihant-arden-ckt-1', dt.id, 44, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Ramp light 12W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Ramp light 12W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-arihant-arden-ckt-1-dev-2', 'bf-arihant-arden-ckt-1', dt.id, 9, 12, 12,
       true, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Ramp light 12W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-arihant-arden-ckt-1-demo-1', 'bf-arihant-arden-ckt-1', 1, 44,
        22.54, 8.92, 60.42590949423248, false,
        NULL, '8 pre days 15-22 Jul 2025 averaging 22.5388 against a stated 22.54, then 6 days 24-29 Jul averaging 8.9233 against 8.92. Metered count is the 44 tube lights; the 9 ramp lights share the circuit and the meter but are excluded from the calculation.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-pre-2025-07-15', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-15'::date, 22.75, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-pre-2025-07-16', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-16'::date, 22.63, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-pre-2025-07-17', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-17'::date, 22.73, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-pre-2025-07-18', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-18'::date, 22.37, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-pre-2025-07-19', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-19'::date, 22.75, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-pre-2025-07-20', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-20'::date, 22.76, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-pre-2025-07-21', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-21'::date, 22.16, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-pre-2025-07-22', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-22'::date, 22.16, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-post-2025-07-24', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-24'::date, 9.38, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-post-2025-07-25', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-25'::date, 8.89, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-post-2025-07-26', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-26'::date, 9.12, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-post-2025-07-27', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-27'::date, 9.05, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-post-2025-07-28', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-28'::date, 8.8, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-arihant-arden-ckt-1-demo-1-post-2025-07-29', 'bf-arihant-arden-ckt-1-demo-1',
        '2025-07-29'::date, 8.3, 'post') ON CONFLICT DO NOTHING;
UPDATE circuits
   SET benchmark_override_pct = 64.12,
       benchmark_override_reason = 'Agreement states 64.12%; the demos on record give 60.4259%. The agreed figure is what this society is billed against.',
       benchmark_override_by_id = (SELECT a.id FROM admin_users a WHERE a.id = 'sys-data-import'),
       benchmark_override_at = now()
 WHERE id = 'bf-arihant-arden-ckt-1' AND benchmark_override_pct IS NULL;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-arihant-arden-demo-report', 'bf-arihant-arden-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-arihant-arden-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 44, "representedLightCount": 750, "extrapolationFactor": 17.045455, "preInstallBaseline": 22.54, "postInstallAverage": 8.92, "savedKwhPerDay": 13.62, "benchmarkSavingsPct": 64.12, "projectedSavedKwhPerDay": 246.352, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2025-11-27'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-arihant-arden-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-arihant-arden-offer', 'bf-arihant-arden-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-arihant-arden-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 44, "representedLightCount": 750, "benchmarkSavingsPct": 64.12, "preInstallBaseline": 22.54, "projectedSavedKwhPerDay": 14.4526}]'::jsonb,
       10, 67.9075, 6.30, 36,
       14001.00, '2025-11-27'::date, a.id,
       '2025-11-27'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'Arihant Arden'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-arihant-arden-agreement', 'bf-arihant-arden-pipe', 'bf-arihant-arden-offer', '2025-11-27'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2025-11-27'::date, '2025-11-27'::date,
       '2025-11-27'::date,
       'Documents/Arihant_Arden/2025-11/Agreements/Arihant_Arden_Agreement_2025-11-27.pdf',
       'Arihant_Arden_Agreement_2025-11-27.pdf',
       -- The scan reaches us the day after signing.
       ('2025-11-27'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-arihant-arden-contract', 'bf-arihant-arden-pipe', s.id, 'lighting', 'bf-arihant-arden-agreement', 'active',
       '2026-01-01'::date, ('2026-01-01'::date + '36 months'::interval),
       '2026-01-01'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Arihant Arden' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-arihant-arden-terms', 'bf-arihant-arden-contract', 1, '2026-01-01'::date, 'negotiated_fixed',
       10, 67.9075, 6.30,
       '[{"circuitId": "bf-arihant-arden-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 44, "representedLightCount": 750, "benchmarkSavingsPct": 64.12, "preInstallBaseline": 22.54, "projectedSavedKwhPerDay": 14.4526}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
