-- Societies commissioned before this system existed: Bestech Park View Residency.
--
-- Each was read from two documents — its signed agreement and its
-- post-installation savings report — into one pipeline, survey, circuit set,
-- demo set and contract. Generated by
--   scripts/backfill-sql.py --migration --only "Bestech Park View Residency"
-- Do not edit by hand, and do not add a society to it once it has been
-- applied anywhere: Prisma checksums an applied migration, so appending
-- would be reported as a modified migration on the next deploy — and the new
-- rows would not land, because this one is already recorded as done. Add
-- another migration instead.

-- Generated by scripts/backfill-sql.py — do not edit by hand.
-- 2026-08-28


-- ═══ Bestech Park View Residency ═════════════════════════════════

-- Runs once per database, deletes nothing, and is a no-op
-- wherever the rows are already present.
-- (the DELETEs below are suppressed in migration mode)
/*
DELETE FROM contract_term_versions WHERE contract_id = 'bf-bestech-park-view-residency-contract';
DELETE FROM contracts   WHERE id = 'bf-bestech-park-view-residency-contract';
DELETE FROM agreements  WHERE id = 'bf-bestech-park-view-residency-agreement';
DELETE FROM offers      WHERE id = 'bf-bestech-park-view-residency-offer';
DELETE FROM demo_reports WHERE id = 'bf-bestech-park-view-residency-demo-report';
DELETE FROM circuit_demo_readings WHERE demo_id IN (SELECT id FROM circuit_demos WHERE circuit_id LIKE 'bf-bestech-park-view-residency-ckt-%');
DELETE FROM circuit_demos   WHERE circuit_id LIKE 'bf-bestech-park-view-residency-ckt-%';
DELETE FROM meter_readings  WHERE circuit_id LIKE 'bf-bestech-park-view-residency-ckt-%';
DELETE FROM circuit_devices WHERE circuit_id LIKE 'bf-bestech-park-view-residency-ckt-%';
DELETE FROM circuits    WHERE id LIKE 'bf-bestech-park-view-residency-ckt-%';
DELETE FROM site_surveys WHERE id = 'bf-bestech-park-view-residency-survey';
DELETE FROM pipelines   WHERE id = 'bf-bestech-park-view-residency-pipe';
DELETE FROM engagements WHERE id = 'bf-bestech-park-view-residency-eng';*/

-- The society must already exist, and exactly once. These were imported with
-- their flat counts and portal accounts, so a missing one is a mistake to
-- stop on rather than paper over by inserting a second row — and a DUPLICATE
-- one is worse, because every statement below matches by name and would
-- quietly write to both.
DO $$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM societies WHERE name = 'Bestech Park View Residency';
  IF n = 0 THEN RAISE EXCEPTION 'no society named %', 'Bestech Park View Residency'; END IF;
  IF n > 1 THEN RAISE EXCEPTION '% societies named % — resolve the duplicate first', n, 'Bestech Park View Residency'; END IF;
END $$;

UPDATE societies SET status = 'active' WHERE name = 'Bestech Park View Residency';   -- address left as stored

INSERT INTO engagements (id, society_id, service_line, status, created_at)
SELECT 'bf-bestech-park-view-residency-eng', s.id, 'lighting', 'active', now() FROM societies s WHERE s.name = 'Bestech Park View Residency' ON CONFLICT DO NOTHING;

INSERT INTO pipelines (id, society_id, service_line, stage, contact_name, contact_phone,
                       meeting_date, sales_owner_id, logged_by_id, authoritative, notes,
                       created_at, updated_at)
SELECT 'bf-bestech-park-view-residency-pipe', s.id, 'lighting', 'active_billing',
       'Bestech Park View Residency', NULL, '2026-02-05'::date,
       a.id, a.id, true,
       'Backfilled from the signed agreement, the post-installation savings report and the first invoice. This deal predates the system: the date above is the agreement signature, not a meeting.',
       now(), now()
FROM societies s, admin_users a WHERE s.name = 'Bestech Park View Residency' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO site_surveys (id, pipeline_id, created_at) VALUES ('bf-bestech-park-view-residency-survey', 'bf-bestech-park-view-residency-pipe', now()) ON CONFLICT DO NOTHING;

INSERT INTO circuits (id, society_id, site_survey_id, service_line, light_type,
                      metered_light_count, represented_light_count, wattage, working_hours,
                      state, location, meter_installed_at, light_replacement_date,
                      pre_install_baseline, benchmark_savings_pct, eligibility_checklist,
                      created_by_id, created_at)
SELECT 'bf-bestech-park-view-residency-ckt-1', s.id, 'bf-bestech-park-view-residency-survey', 'lighting', 'basement',
       47, 400, 20, 24,
       'benchmark_confirmed', 'Basement',
       '2025-09-13'::date, '2025-09-22'::date,
       23.80, 67.10,
       jsonb_build_object('backfilled', true, 'source', 'signed agreement + post-installation savings report',
                          'note', 'Commissioned before this system existed — CON-16 eligibility was never assessed.'),
       a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Bestech Park View Residency' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO lighting_inventory_areas (id, site_survey_id, area, light_type, count, method, note, created_at)
VALUES ('bf-bestech-park-view-residency-ckt-1-inv', 'bf-bestech-park-view-residency-survey', 'Basement', 'basement',
        400, 'estimated',
        'Read from the society''s own documents — its first invoice and post-installation savings report. The site was never walked; this society was commissioned before this system existed.',
        now()) ON CONFLICT DO NOTHING;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM device_types WHERE name = 'Tube light 20W' AND role = 'original' AND deleted_at IS NULL) THEN
    RAISE EXCEPTION 'device type % is not in the catalog', 'Tube light 20W';
  END IF;
END $$;
INSERT INTO circuit_devices (id, circuit_id, device_type_id, count, wattage, hours_per_day,
                             excluded_from_calculation, historical, historical_note, recorded_by_id, created_at)
SELECT 'bf-bestech-park-view-residency-ckt-1-dev-1', 'bf-bestech-park-view-residency-ckt-1', dt.id, 47, 20, 24,
       false, true, 'Read from the post-installation savings report', a.id, now()
FROM device_types dt, admin_users a
WHERE dt.name = 'Tube light 20W' AND dt.role = 'original' AND dt.deleted_at IS NULL
  AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
INSERT INTO circuit_demos (id, circuit_id, sequence, metered_light_count,
                           pre_install_baseline, post_install_average, savings_pct,
                           rejected, rejection_reason, note, created_at)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1', 'bf-bestech-park-view-residency-ckt-1', 1, 47,
        23.8, 7.83, 67.10084033613445, false,
        NULL, '6 pre days 14-19 Sep 2025 averaging 23.7983 against a stated 23.80, then 7 days 23-29 Sep averaging 7.8314 against 7.83. Transcribed from the user''s pasted text; no file was supplied.', now()) ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-pre-2025-09-14', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-14'::date, 23.51, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-pre-2025-09-15', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-15'::date, 23.56, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-pre-2025-09-16', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-16'::date, 23.75, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-pre-2025-09-17', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-17'::date, 23.98, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-pre-2025-09-18', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-18'::date, 23.98, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-pre-2025-09-19', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-19'::date, 24.01, 'pre') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-post-2025-09-23', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-23'::date, 7.93, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-post-2025-09-24', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-24'::date, 7.95, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-post-2025-09-25', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-25'::date, 7.81, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-post-2025-09-26', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-26'::date, 7.49, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-post-2025-09-27', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-27'::date, 8.05, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-post-2025-09-28', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-28'::date, 7.81, 'post') ON CONFLICT DO NOTHING;
INSERT INTO circuit_demo_readings (id, demo_id, date, kwh, phase)
VALUES ('bf-bestech-park-view-residency-ckt-1-demo-1-post-2025-09-29', 'bf-bestech-park-view-residency-ckt-1-demo-1',
        '2025-09-29'::date, 7.78, 'post') ON CONFLICT DO NOTHING;

-- The demo report. Not needed for billing, but without it the deal map sits
-- at "Demo savings report · In progress" while every later step reads done.
INSERT INTO demo_reports (id, pipeline_id, version, status,
                          pre_install_baseline_total, post_install_average_total, measured_savings_pct,
                          society_light_count, metered_light_count, extrapolation_factor,
                          projected_savings_kwh_per_day, circuit_snapshot, generated_at, shared_at, shared_by_id)
SELECT 'bf-bestech-park-view-residency-demo-report', 'bf-bestech-park-view-residency-pipe', 1, 'shared',
       c.pre_install_baseline, c.pre_install_baseline * (1 - c.benchmark_savings_pct / 100),
       c.benchmark_savings_pct, c.represented_light_count, c.metered_light_count,
       c.represented_light_count::double precision / c.metered_light_count,
       (c.pre_install_baseline * c.benchmark_savings_pct / 100)
         * (c.represented_light_count::double precision / c.metered_light_count),
       '[{"circuitId": "bf-bestech-park-view-residency-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 47, "representedLightCount": 400, "extrapolationFactor": 8.510638, "preInstallBaseline": 23.8, "postInstallAverage": 7.83, "savedKwhPerDay": 15.97, "benchmarkSavingsPct": 67.1, "projectedSavedKwhPerDay": 135.9132, "preInstallReadings": [], "postInstallReadings": []}]'::jsonb, now(), '2026-02-05'::date, a.id
FROM circuits c, admin_users a
-- shared_by_id is an ADMIN, not a profile: FirsThing shares the report WITH
-- the society, so the sharer is internal. The mirror of offers, where
-- responded_by_id IS a profile because accepting is the society's act.
WHERE c.id = 'bf-bestech-park-view-residency-ckt-1' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO offers (id, pipeline_id, version, status, benchmark_source, circuit_terms,
                    tolerance_pct, revenue_share_pct, unit_electricity_rate, term_months,
                    projected_monthly_fee, issued_at, issued_by_id, responded_at, responded_by_id, created_at)
SELECT 'bf-bestech-park-view-residency-offer', 'bf-bestech-park-view-residency-pipe', 1, 'accepted', 'negotiated_fixed', '[{"circuitId": "bf-bestech-park-view-residency-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 47, "representedLightCount": 400, "benchmarkSavingsPct": 67.1, "preInstallBaseline": 23.8, "projectedSavedKwhPerDay": 15.9698}]'::jsonb,
       10, 52.4799, 6.50, 36,
       11938.00, '2026-02-05'::date, a.id,
       '2026-02-05'::date, p.id, now()
FROM admin_users a
LEFT JOIN societies soc ON soc.name = 'Bestech Park View Residency'
LEFT JOIN profiles p ON p.society_id = soc.id AND p.portal_authority = 'office_bearer' AND p.is_active
WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO agreements (id, pipeline_id, offer_id, prepared_at, prepared_by_id,
                        printed_at, notarized_at, signed_at,
                        executed_s3_key, executed_file_name, uploaded_at, uploaded_by_id)
SELECT 'bf-bestech-park-view-residency-agreement', 'bf-bestech-park-view-residency-pipe', 'bf-bestech-park-view-residency-offer', '2026-02-05'::date, a.id,
       -- Printed and notarised are the same day, and it is the e-stamp
       -- certificate date on page 1 (the user, 2026-08-27). It can fall after
       -- the front-page date, which is a backdated effective date rather than
       -- a mistake.
       '2026-02-05'::date, '2026-02-05'::date,
       '2026-02-05'::date,
       'Documents/Bestech_Park_View_Residency/2026-02/Agreements/Bestech_Park_View_Residency_Agreement_2026-02-05.pdf',
       'Bestech_Park_View_Residency_Agreement_2026-02-05.pdf',
       -- The scan reaches us the day after signing.
       ('2026-02-05'::date + 1), a.id
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contracts (id, pipeline_id, society_id, service_line, agreement_id, status,
                       term_start, term_end, activated_at, activated_by_id, created_at)
SELECT 'bf-bestech-park-view-residency-contract', 'bf-bestech-park-view-residency-pipe', s.id, 'lighting', 'bf-bestech-park-view-residency-agreement', 'active',
       '2026-03-15'::date, ('2026-03-15'::date + '36 months'::interval),
       '2026-03-15'::date, a.id, now()
FROM societies s, admin_users a WHERE s.name = 'Bestech Park View Residency' AND a.id = 'sys-data-import' ON CONFLICT DO NOTHING;

INSERT INTO contract_term_versions (id, contract_id, version, effective_from, benchmark_source,
                                    tolerance_pct, revenue_share_pct, unit_electricity_rate,
                                    circuit_benchmarks, recorded_by_id, recorded_at)
SELECT 'bf-bestech-park-view-residency-terms', 'bf-bestech-park-view-residency-contract', 1, '2026-03-15'::date, 'negotiated_fixed',
       10, 52.4799, 6.50,
       '[{"circuitId": "bf-bestech-park-view-residency-ckt-1", "lightType": "basement", "location": "Basement", "meteredLightCount": 47, "representedLightCount": 400, "benchmarkSavingsPct": 67.1, "preInstallBaseline": 23.8, "projectedSavedKwhPerDay": 15.9698}]'::jsonb, a.id, now()
FROM admin_users a WHERE a.id = 'sys-data-import' ON CONFLICT DO NOTHING;
